# @see https://github.com/DataDog/benchmarking-platform-tools/blob/main/images/templates/gitlab/build-ci-images.template.yml
include:
  project: 'DataDog/benchmarking-platform-tools'
  file: 'images/templates/gitlab/build-ci-images.template.yml'

variables:
  # Image suffix that is used for building dd-trace-go microbenchmarks Docker image. Don't change!
  BASE_CI_IMAGE_SUFFIX: dd-trace-go-${CI_PIPELINE_ID}
  BASE_CI_IMAGE_CONTAINER_DIR: .gitlab/benchmarks/micro/container

  # Benchmarks image is created here: https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-go/-/jobs/1657729516
  BENCHMARKS_CI_IMAGE: registry.ddbuild.io/ci/benchmarking-platform:dd-trace-go-111525540

  # Changes smaller than SIGNIFICANT_IMPACT_THRESHOLD will be treated as a noise
  SIGNIFICANT_IMPACT_THRESHOLD: 2.0

.benchmark-rules: &benchmark-rules
  - if: '$CI_COMMIT_TAG =~ /^.*\/v\d+\.\d+\.\d+(?:-.*\.\d+)?$/'
    when: never
  - if: '$CI_COMMIT_BRANCH =~ /^graphite-base\/.*$/'
    when: never
  - if: '$CI_COMMIT_BRANCH =~ /^mq-working-branch-.*$/'
    when: never
  - if: '$CI_COMMIT_BRANCH == "main"'
    when: always
    interruptible: false
  - when: always
    interruptible: true

.microbenchmarks:
  stage: microbenchmarks
  image: $BENCHMARKS_CI_IMAGE
  rules: *benchmark-rules
  timeout: 45m
  tags: ["runner:apm-k8s-m8g-metal"]
  needs: []
  variables:
    GOTOOLCHAIN: auto

    KUBERNETES_CPU_REQUEST: "48"
    KUBERNETES_CPU_LIMIT: "48"
  script:
    - export GO_VERSION=$(go version | sed 's/go version //')
    - export S3_URL=s3://relenv-benchmarking-data/${CI_PROJECT_NAME}/${CI_COMMIT_REF_NAME}/${PARENT_PIPELINE_ID}/${CI_JOB_ID}/
    - bp-runner .gitlab/benchmarks/micro/bp-runner.yml --debug
  retry:
    max: 2
    when:
      - unknown_failure
      - data_integrity_failure
      - runner_system_failure
      - scheduler_failure
      - api_failure
  artifacts:
    name: "artifacts"
    when: always
    paths:
      - artifacts/
    expire_in: "30 days"


# Please set maximum 24 scenarios per group!
# One single CI job has up to 24 CPU cores, thus 24 benchmarks per group is max.
#
# parallel:matrix can't be used, because of bug https://gitlab.com/gitlab-org/gitlab/-/work_items/285853#note_2781385941
# i.e. CI job names can't be larger than 255 characters.
microbenchmarks-1:
  extends: .microbenchmarks
  variables:
    BENCHMARKS: "BenchmarkConfig|BenchmarkStartSpanConfig|BenchmarkGraphQL|BenchmarkSampleWAFContext|BenchmarkCaptureStackTrace|BenchmarkSetTagString|BenchmarkSetTagStringPtr|BenchmarkSetTagMetric|BenchmarkSetTagStringer|BenchmarkSerializeSpanLinksInMeta|BenchmarkLogs|BenchmarkParallelLogs|BenchmarkMetrics|BenchmarkParallelMetrics|BenchmarkPayloadVersions|BenchmarkOTLPTraceWriterAdd|BenchmarkOTLPTraceWriterFlush|BenchmarkOTLPProtoMarshal|BenchmarkOTLPProtoSize|BenchmarkOTLPTraceWriterConcurrent"
    CPUS_PER_BENCHMARK: 1
    REPETITIONS: 1
    GROUP_ID: "group-1"

microbenchmarks-2:
  extends: .microbenchmarks
  variables:
    BENCHMARKS: "BenchmarkStartRequestSpan|BenchmarkHttpServeTrace|BenchmarkTracerAddSpans|BenchmarkStartSpan|BenchmarkSingleSpanRetention|BenchmarkOTelApiWithCustomTags|BenchmarkInjectW3C|BenchmarkExtractW3C|BenchmarkPartialFlushing"
    CPUS_PER_BENCHMARK: 1
    REPETITIONS: 1
    GROUP_ID: "group-2"

pr-performance-gates:
  stage: microbenchmarks
  needs: [microbenchmarks-1, microbenchmarks-2]
  when: on_success
  tags:
    - "arch:amd64"
  image: $BASE_CI_IMAGE
  script:
    - bp-runner .gitlab/benchmarks/pr-gate.thresholds.yml --debug
  artifacts:
    name: "artifacts"
    when: always
    paths:
      - artifacts/
    expire_in: "30 days"
