name: Run service
description: Runs a Docker image from cache
inputs:
  repository:
    required: true
    description: The repository of the image to warm up
  tag:
    required: true
    description: The tag of the image to warm up (latest tag not supported)
  flags:
    required: true
    description: The flags to pass to the service
runs:
  using: "composite"
  steps:
    - name: Build cache filename
      id: build_cache_filename
      shell: bash
      run: |
        cache_filename=$(printf '%s_%s' "${{ inputs.repository }}" "${{ inputs.tag }}" | tr -cs '[:alnum:]_' '_')
        echo "cache_filename=$cache_filename" >> $GITHUB_OUTPUT
    - name: Restore image cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ${{ steps.build_cache_filename.outputs.cache_filename }}.tar
        key: ${{ inputs.repository }}:${{ inputs.tag }}
    - name: Load image
      shell: bash
      run: |
        docker load -i ${{ steps.build_cache_filename.outputs.cache_filename }}.tar
    - name: Run service
      shell: bash
      run: |
        docker run -d ${{ inputs.flags }} ${{ inputs.repository }}:${{ inputs.tag }}
