// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016 Datadog, Inc.

package api

import (
	"context"

	v2 "github.com/DataDog/dd-trace-go/contrib/google.golang.org/api/v2"
)

// An Option customizes the config.
type Option = v2.Option

// WithContext sets the context in the config. This can be used to set span
// parents or pass a context through to the underlying client constructor.
func WithContext(ctx context.Context) Option {
	return v2.WithContext(ctx)
}

// WithScopes sets the scopes used to create the oauth2 config for Google APIs.
func WithScopes(scopes ...string) Option {
	return v2.WithScopes(scopes...)
}

// WithServiceName sets the service name in the config. The default service
// name is inferred from the API definitions based on the http request route.
func WithServiceName(serviceName string) Option {
	return v2.WithService(serviceName)
}

// WithAnalytics enables Trace Analytics for all started spans.
func WithAnalytics(on bool) Option {
	return v2.WithAnalytics(on)
}

// WithAnalyticsRate sets the sampling rate for Trace Analytics events
// correlated to started spans.
func WithAnalyticsRate(rate float64) Option {
	return v2.WithAnalyticsRate(rate)
}

// WithEndpointMetadataDisabled allows to disable the enriched Google endpoint metadata behavior for
// this integration. Use this option if you are sensitive to changes in some span tags generated by this integration
// that might happen when the used Google endpoint metadata gets regenerated in newer dd-trace-go versions.
func WithEndpointMetadataDisabled() Option {
	return v2.WithEndpointMetadataDisabled()
}
