ignored = [
  # From these libraries we should always ensure compatibility with the latest:
  "github.com/opentracing/*",
  "golang.org/x/*",
  "google.golang.org/appengine/*",
]

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  version = "v3.3.1"
