// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2024 Datadog, Inc.

// Code generated by github.com/DataDog/dd-trace-go/v2/scripts/gencontribdoc. DO NOT EDIT.

// The purpose of the packages held in contrib is to provide tracing on top of commonly used
// packages from the standard library as well as the community in a "plug-and-play" manner.
// This means that by simply importing the appropriate path, functions are exposed having
// the same signature as the original package. These functions return structures that embed
// the original return value, allowing them to be used as they normally would with tracing
// activated out of the box.
//
// All of these libraries are supported by our https://www.datadoghq.com/apm/.
//
// # Integrations
//
// Each integration is published as its own module:
//   - [contrib/99designs/gqlgen/v2]
//   - [contrib/IBM/sarama/v2]
//   - [contrib/Shopify/sarama/v2]
//   - [contrib/aerospike/aerospike-client-go.v7/v2]
//   - [contrib/aws/aws-sdk-go-v2/v2]
//   - [contrib/aws/aws-sdk-go/v2]
//   - [contrib/aws/datadog-lambda-go/v2]
//   - [contrib/azure/apim-callout/v2]
//   - [contrib/bradfitz/gomemcache/v2]
//   - [contrib/cloud.google.com/go/pubsub.v1/v2]
//   - [contrib/cloud.google.com/go/pubsub.v2/v2]
//   - [contrib/confluentinc/confluent-kafka-go/kafka.v2/v2]
//   - [contrib/confluentinc/confluent-kafka-go/kafka/v2]
//   - [contrib/database/sql/v2]
//   - [contrib/dimfeld/httptreemux.v5/v2]
//   - [contrib/elastic/go-elasticsearch.v6/v2]
//   - [contrib/emicklei/go-restful.v3/v2]
//   - [contrib/envoyproxy/go-control-plane/v2]
//   - [contrib/gin-gonic/gin/v2]
//   - [contrib/globalsign/mgo/v2]
//   - [contrib/go-chi/chi.v5/v2]
//   - [contrib/go-chi/chi/v2]
//   - [contrib/go-pg/pg.v10/v2]
//   - [contrib/go-redis/redis.v7/v2]
//   - [contrib/go-redis/redis.v8/v2]
//   - [contrib/go-redis/redis/v2]
//   - [contrib/go.mongodb.org/mongo-driver.v2/v2]
//   - [contrib/go.mongodb.org/mongo-driver/v2]
//   - [contrib/go.uber.org/zap/v2]
//   - [contrib/gocql/gocql/v2]
//   - [contrib/gofiber/fiber.v2/v2]
//   - [contrib/gomodule/redigo/v2]
//   - [contrib/google.golang.org/api/v2]
//   - [contrib/google.golang.org/grpc/v2]
//   - [contrib/gorilla/mux/v2]
//   - [contrib/gorm.io/gorm.v1/v2]
//   - [contrib/graph-gophers/graphql-go/v2]
//   - [contrib/graphql-go/graphql/v2]
//   - [contrib/haproxy/stream-processing-offload/v2]
//   - [contrib/hashicorp/consul/v2]
//   - [contrib/hashicorp/vault/v2]
//   - [contrib/jackc/pgx.v5/v2]
//   - [contrib/jmoiron/sqlx/v2]
//   - [contrib/julienschmidt/httprouter/v2]
//   - [contrib/k8s.io/client-go/v2]
//   - [contrib/k8s.io/gateway-api/v2]
//   - [contrib/labstack/echo.v4/v2]
//   - [contrib/labstack/echo.v5/v2]
//   - [contrib/log/slog/v2]
//   - [contrib/mark3labs/mcp-go/v2]
//   - [contrib/miekg/dns/v2]
//   - [contrib/modelcontextprotocol/go-sdk/v2]
//   - [contrib/net/http/v2]
//   - [contrib/olivere/elastic.v5/v2]
//   - [contrib/redis/go-redis.v9/v2]
//   - [contrib/redis/rueidis/v2]
//   - [contrib/rs/zerolog/v2]
//   - [contrib/segmentio/kafka-go/v2]
//   - [contrib/sirupsen/logrus/v2]
//   - [contrib/syndtr/goleveldb/v2]
//   - [contrib/tidwall/buntdb/v2]
//   - [contrib/twitchtv/twirp/v2]
//   - [contrib/twmb/franz-go/v2]
//   - [contrib/uptrace/bun/v2]
//   - [contrib/urfave/negroni/v2]
//   - [contrib/valkey-io/valkey-go/v2]
//   - [contrib/valyala/fasthttp/v2]
//
// [contrib/99designs/gqlgen/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/99designs/gqlgen/v2
// [contrib/IBM/sarama/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/IBM/sarama/v2
// [contrib/Shopify/sarama/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/Shopify/sarama/v2
// [contrib/aerospike/aerospike-client-go.v7/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/aerospike/aerospike-client-go.v7/v2
// [contrib/aws/aws-sdk-go-v2/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/aws/aws-sdk-go-v2/v2
// [contrib/aws/aws-sdk-go/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/aws/aws-sdk-go/v2
// [contrib/aws/datadog-lambda-go/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/aws/datadog-lambda-go/v2
// [contrib/azure/apim-callout/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/azure/apim-callout/v2
// [contrib/bradfitz/gomemcache/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/bradfitz/gomemcache/v2
// [contrib/cloud.google.com/go/pubsub.v1/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/cloud.google.com/go/pubsub.v1/v2
// [contrib/cloud.google.com/go/pubsub.v2/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/cloud.google.com/go/pubsub.v2/v2
// [contrib/confluentinc/confluent-kafka-go/kafka.v2/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/confluentinc/confluent-kafka-go/kafka.v2/v2
// [contrib/confluentinc/confluent-kafka-go/kafka/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/confluentinc/confluent-kafka-go/kafka/v2
// [contrib/database/sql/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/database/sql/v2
// [contrib/dimfeld/httptreemux.v5/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/dimfeld/httptreemux.v5/v2
// [contrib/elastic/go-elasticsearch.v6/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/elastic/go-elasticsearch.v6/v2
// [contrib/emicklei/go-restful.v3/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/emicklei/go-restful.v3/v2
// [contrib/envoyproxy/go-control-plane/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/envoyproxy/go-control-plane/v2
// [contrib/gin-gonic/gin/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/gin-gonic/gin/v2
// [contrib/globalsign/mgo/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/globalsign/mgo/v2
// [contrib/go-chi/chi.v5/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/go-chi/chi.v5/v2
// [contrib/go-chi/chi/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/go-chi/chi/v2
// [contrib/go-pg/pg.v10/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/go-pg/pg.v10/v2
// [contrib/go-redis/redis.v7/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/go-redis/redis.v7/v2
// [contrib/go-redis/redis.v8/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/go-redis/redis.v8/v2
// [contrib/go-redis/redis/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/go-redis/redis/v2
// [contrib/go.mongodb.org/mongo-driver.v2/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/go.mongodb.org/mongo-driver.v2/v2
// [contrib/go.mongodb.org/mongo-driver/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/go.mongodb.org/mongo-driver/v2
// [contrib/go.uber.org/zap/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/go.uber.org/zap/v2
// [contrib/gocql/gocql/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/gocql/gocql/v2
// [contrib/gofiber/fiber.v2/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/gofiber/fiber.v2/v2
// [contrib/gomodule/redigo/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/gomodule/redigo/v2
// [contrib/google.golang.org/api/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/google.golang.org/api/v2
// [contrib/google.golang.org/grpc/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/google.golang.org/grpc/v2
// [contrib/gorilla/mux/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/gorilla/mux/v2
// [contrib/gorm.io/gorm.v1/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/gorm.io/gorm.v1/v2
// [contrib/graph-gophers/graphql-go/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/graph-gophers/graphql-go/v2
// [contrib/graphql-go/graphql/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/graphql-go/graphql/v2
// [contrib/haproxy/stream-processing-offload/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/haproxy/stream-processing-offload/v2
// [contrib/hashicorp/consul/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/hashicorp/consul/v2
// [contrib/hashicorp/vault/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/hashicorp/vault/v2
// [contrib/jackc/pgx.v5/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/jackc/pgx.v5/v2
// [contrib/jmoiron/sqlx/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/jmoiron/sqlx/v2
// [contrib/julienschmidt/httprouter/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/julienschmidt/httprouter/v2
// [contrib/k8s.io/client-go/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/k8s.io/client-go/v2
// [contrib/k8s.io/gateway-api/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/k8s.io/gateway-api/v2
// [contrib/labstack/echo.v4/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/labstack/echo.v4/v2
// [contrib/labstack/echo.v5/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/labstack/echo.v5/v2
// [contrib/log/slog/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/log/slog/v2
// [contrib/mark3labs/mcp-go/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/mark3labs/mcp-go/v2
// [contrib/miekg/dns/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/miekg/dns/v2
// [contrib/modelcontextprotocol/go-sdk/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/modelcontextprotocol/go-sdk/v2
// [contrib/net/http/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/net/http/v2
// [contrib/olivere/elastic.v5/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/olivere/elastic.v5/v2
// [contrib/redis/go-redis.v9/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/redis/go-redis.v9/v2
// [contrib/redis/rueidis/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/redis/rueidis/v2
// [contrib/rs/zerolog/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/rs/zerolog/v2
// [contrib/segmentio/kafka-go/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/segmentio/kafka-go/v2
// [contrib/sirupsen/logrus/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/sirupsen/logrus/v2
// [contrib/syndtr/goleveldb/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/syndtr/goleveldb/v2
// [contrib/tidwall/buntdb/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/tidwall/buntdb/v2
// [contrib/twitchtv/twirp/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/twitchtv/twirp/v2
// [contrib/twmb/franz-go/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/twmb/franz-go/v2
// [contrib/uptrace/bun/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/uptrace/bun/v2
// [contrib/urfave/negroni/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/urfave/negroni/v2
// [contrib/valkey-io/valkey-go/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/valkey-io/valkey-go/v2
// [contrib/valyala/fasthttp/v2]: https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/valyala/fasthttp/v2
package contrib

//go:generate go run ../scripts/gencontribdoc/main.go .. contrib.go
