# Configuration file for actionlint
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  # Labels for self-hosted runners used in workflows
  labels:
    - APM Larger Runners
