version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - forbidigo
    - govet
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: internal/env/
        linters:
          - forbidigo
  settings:
    forbidigo:
      forbid:
        - pattern: "^os\\.Getenv$"
          msg: "use internal/env.GetEnv instead of os.Getenv"
        - pattern: "^os\\.LookupEnv$"
          msg: "use internal/env.LookupEnv instead of os.LookupEnv"
      exclude_godoc_examples: true
      analyze_types: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow # TODO: Enable this once we've fixed all the shadowing issues.
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0