version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - govet
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow # TODO: Enable this once we've fixed all the shadowing issues.
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
