run:
  deadline: 10m
  skip-dirs:
    # This package is an exception and has its own test job (Testing outlier gRPC v1.2).
    - contrib/google.golang.org/grpc.v12
linters:
  disable-all: true
  enable:
  - gofmt
  - revive
  - bodyclose
