run:
  deadline: 10m
  build-tags:
    - appsec
linters:
  disable-all: true
  enable:
  - gofmt
  - revive
  - bodyclose
linters-settings:
  gci:
    sections:
      - standard
      - prefix(github.com/DataDog/dd-trace-go/v2)
      - default
    skip-generated: true
    custom-order: true
