codecov:
  branch: main

comment: false

flags:
  core:
    carryforward: true
    paths:
      - ddtrace/*
      - internal/*
      - profiler/*
  contrib:
    carryforward: true
    paths:
      - contrib/*

github_checks:
  annotations: false
