comment: off

coverage:
  status:
    project:
      default: false
      core:
        target: 80%
        flags:
          - core
      contrib:
        target: 75%
        flags:
          - contrib
    patch: yes

flags:
  core:
    paths:
      - ddtrace/*
            - internal/*
            - profiler/*
  contrib:
    paths:
      - contrib/*