comment: false

coverage:
  status:
    project:
      default: false
      core:
        target: 80%
        flags:
          - core
      contrib:
        target: 75%
        flags:
          - contrib
    patch:
      default:
        target: 90%
        # Only run this check for pull requests, but skip it for merged
        # commits. This highlights patches with potential coverage problems
        # during development, but doesn't make our v1 (release) branch look
        # like it fails CI checks as we consider this check to be optional.
        only_pulls: true

flags:
  core:
    paths:
      - ddtrace/*
            - internal/*
            - profiler/*
  contrib:
    paths:
      - contrib/*

github_checks:
  annotations: false
