codecov:
  branch: main

# Disable PR comments
comment: false

# Disable CI status checks
coverage:
  status:
    project: off
    patch: off

flags:
  core:
    carryforward: true
    paths:
      - ddtrace/*
      - internal/*
      - profiler/*
  contrib:
    carryforward: true
    paths:
      - contrib/*

github_checks:
  annotations: false
