codecov:
  branch: main

comment:
  layout: "reach, diff, flags, files"
  behavior: new
  require_changes: false  # if true: only post the comment if coverage changes

flags:
  core:
    paths:
      - ddtrace/*
      - internal/*
      - profiler/*
  contrib:
    paths:
      - contrib/*

github_checks:
  annotations: false
