codecov:
  branch: main

comment:
  layout: "header, files"

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

flags:
  core:
    carryforward: true
    paths:
      - ddtrace/*
      - internal/*
      - profiler/*
  contrib:
    carryforward: true
    paths:
      - contrib/*

# disable annotations as they can be noisy
github_checks:
  annotations: false
