services:
  aerospike:
    image: aerospike:ce-8.2.0.0_1@sha256:e4ef5da23cf7979b49ea250c184a94d35d183a0049548b3f3a184055ca378cef
    ports:
      - "3000:3000"
  cassandra:
    image: cassandra:5@sha256:1d18946ead0b0d22ed0371bd7384d86f540465c489f2935e88df35e755073f6b
    environment:
      JVM_OPTS: "-Xms750m -Xmx750m"
      CASSANDRA_CLUSTER_NAME: "dd-trace-go-test-cluster"
      CASSANDRA_DC: "dd-trace-go-test-datacenter"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
    ports:
      - "9042:9042"
  mysql:
    image: mysql:26@sha256:9d48c42f8341068f199116dfccb919b607c99765b5c61e549a548a43033471a4
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: test
      MYSQL_USER: test
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
  postgres:
    image: postgres:18@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:2b5b581621126574f3d1f75e78d3eebe8d05aedb59ad0cfdf9aa42cb0634d726
    environment:
      SA_PASSWORD: myPassw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  consul:
    image: consul:1.15@sha256:10084bbbed746968b0b9f8edab2f8552e44f117e35b88153a5e0a3ad1e15aa1a
    ports:
      - "8500:8500"
  redis:
    image: redis:8-alpine@sha256:3811787313eba226a2ef38658c6ccb91cd5e110edc89c37767de373120a0e5a0
    ports:
      - "6379:6379"
  valkey:
    image: valkey/valkey:9@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd
    environment:
      VALKEY_EXTRA_FLAGS: "--port 6380 --requirepass password-for-default"
    ports:
      - "6380:6380"
  elasticsearch2:
    image: elasticsearch:5@sha256:d0e119779df7ddf9d476102691d9d0b8783c13434e00d77f01327019c1297839
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
    ports:
      - "9200:9200"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  elasticsearch5:
    image: elasticsearch:5@sha256:d0e119779df7ddf9d476102691d9d0b8783c13434e00d77f01327019c1297839
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
    ports:
      - "9201:9200"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  elasticsearch6:
    image: elasticsearch:9.5.3@sha256:e23d4758358a4e356cc2ef3259a5a6f345cacc1722c10dffe6d7150a1a78e52f
    environment:
      http.port: 9202-9300
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
    ports:
      - "9202:9202"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  elasticsearch7:
    image: elasticsearch:9.5.3@sha256:e23d4758358a4e356cc2ef3259a5a6f345cacc1722c10dffe6d7150a1a78e52f
    environment:
      http.port: 9203-9300
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
    ports:
      - "9203:9203"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  elasticsearch8:
    image: elasticsearch:9.5.3@sha256:e23d4758358a4e356cc2ef3259a5a6f345cacc1722c10dffe6d7150a1a78e52f
    environment:
      http.port: 9204-9300
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
    ports:
      - "9204:9204"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  datadog-agent:
    image: registry.datadoghq.com/agent:latest@sha256:c5bf5ec9be0c51d3d2d47bdadbb82680b5c83ceb9cae8457fe44aa736a1784ad
    environment:
      DD_APM_ENABLED: "true"
      DD_BIND_HOST: "0.0.0.0"
      DD_API_KEY: invalid_key_but_this_is_fine
    ports:
      - "8126:8126"
  testagent:
    image: ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:v1.66.0@sha256:80126beab0e39b171ab86601a99fa599317c5f6ee4cff9e26758ec8e567852ef
    environment:
      LOG_LEVEL: DEBUG
      TRACE_LANGUAGE: golang
      ENABLED_CHECKS: trace_stall,trace_count_header,trace_peer_service,trace_dd_service
      PORT: 9126
      DD_SUPPRESS_TRACE_PARSE_ERRORS: "true"
      DD_POOL_TRACE_CHECK_FAILURES: "true"
      DD_DISABLE_ERROR_RESPONSES: "true"
    ports:
      - "127.0.0.1:9126:9126"
  mongodb3:
    image: mongo:9@sha256:bac22ea7710d774103dcad3ec8ac13cba1eb378f488e3ce8a6b3a1adf2ba9dcc
    ports:
      - "27018:27017"
  mongodb:
    image: mongo:9@sha256:bac22ea7710d774103dcad3ec8ac13cba1eb378f488e3ce8a6b3a1adf2ba9dcc
    ports:
      - "27017:27017"
  memcached:
    image: memcached:1.6-alpine@sha256:9e4de012dc607573052061c0bcb38abc775e1dd59b24e7ac38d1892842094aaf
    ports:
      - "11211:11211"
  kafka:
    image: confluentinc/confluent-local:8.3.2@sha256:2d623f09f1cc46a38b3ace3ee055016617b8f749db1596440bd9ecbe57601d3f
    container_name: kafka
    environment:
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9093,BROKER://0.0.0.0:9092,CONTROLLER://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9093,BROKER://localhost:9092"
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://0.0.0.0:9093,BROKER://0.0.0.0:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "BROKER"
      KAFKA_BROKER_ID: "1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    ports:
      - "9092:9092"
      - "9093:9093"
  localstack:
    image: localstack/localstack:4.14.0@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a
    ports:
      - "4566:4566"
