services:
  aerospike:
    image: aerospike:ce-8.1.2.4_1@sha256:e3ade4ebc112080907c1b45fb61e6c3393fc6147452fe61f5ffc24762080dbac
    ports:
      - "3000:3000"
  cassandra:
    image: cassandra:5@sha256:259578bbeac315a7326c2a99e60eab86f3415e9e895207bf2a032af4de8c16b5
    environment:
      JVM_OPTS: "-Xms750m -Xmx750m"
      CASSANDRA_CLUSTER_NAME: "dd-trace-go-test-cluster"
      CASSANDRA_DC: "dd-trace-go-test-datacenter"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
    ports:
      - "9042:9042"
  mysql:
    image: mysql:26@sha256:66aec17cd21a956029b83f083b813073859e8355dc1a00e55df6ba02f0e32345
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: test
      MYSQL_USER: test
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
  postgres:
    image: postgres:18@sha256:a02db8cac496f15b094798a38254f14d6e00741f709360e5e00bb6668ea31636
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:86cc6144ef39bb0fbed2329e1ad79b13ee82e7b2e4739213a0db0800e668a74a
    environment:
      SA_PASSWORD: myPassw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  consul:
    image: consul:1.15@sha256:10084bbbed746968b0b9f8edab2f8552e44f117e35b88153a5e0a3ad1e15aa1a
    ports:
      - "8500:8500"
  redis:
    image: redis:8-alpine@sha256:978f0e01593e65eed801f2402944efcd936d43b5027e4908a7897baf88ed6241
    ports:
      - "6379:6379"
  valkey:
    image: valkey/valkey:9@sha256:3acc0687f2a2e1091fae6450d7842dd658c941338cf0a873ddd9e14b9e4ea4dd
    environment:
      VALKEY_EXTRA_FLAGS: "--port 6380 --requirepass password-for-default"
    ports:
      - "6380:6380"
  elasticsearch2:
    image: elasticsearch:5@sha256:d0e119779df7ddf9d476102691d9d0b8783c13434e00d77f01327019c1297839
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
    ports:
      - "9200:9200"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  elasticsearch5:
    image: elasticsearch:5@sha256:d0e119779df7ddf9d476102691d9d0b8783c13434e00d77f01327019c1297839
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
    ports:
      - "9201:9200"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  elasticsearch6:
    image: elasticsearch:9.4.4@sha256:5b4517639f5c027e5abc0dbb29dc99e0662b2d060befe17d91c953b88020391d
    environment:
      http.port: 9202-9300
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
    ports:
      - "9202:9202"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  elasticsearch7:
    image: elasticsearch:9.4.4@sha256:5b4517639f5c027e5abc0dbb29dc99e0662b2d060befe17d91c953b88020391d
    environment:
      http.port: 9203-9300
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
    ports:
      - "9203:9203"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  elasticsearch8:
    image: elasticsearch:9.4.4@sha256:5b4517639f5c027e5abc0dbb29dc99e0662b2d060befe17d91c953b88020391d
    environment:
      http.port: 9204-9300
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
    ports:
      - "9204:9204"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  datadog-agent:
    image: registry.datadoghq.com/agent:latest@sha256:5c0fd49a485f100f37beab1969ed68b8027e906acaf81cfec12c16d11e8d9b4e
    environment:
      DD_APM_ENABLED: "true"
      DD_BIND_HOST: "0.0.0.0"
      DD_API_KEY: invalid_key_but_this_is_fine
    ports:
      - "8126:8126"
  testagent:
    image: ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:v1.64.1@sha256:817244a7aec2196c0ad5b09e958a9d1fb40846ecc4257736917aa6b9b55c5e49
    environment:
      LOG_LEVEL: DEBUG
      TRACE_LANGUAGE: golang
      ENABLED_CHECKS: trace_stall,trace_count_header,trace_peer_service,trace_dd_service
      PORT: 9126
      DD_SUPPRESS_TRACE_PARSE_ERRORS: "true"
      DD_POOL_TRACE_CHECK_FAILURES: "true"
      DD_DISABLE_ERROR_RESPONSES: "true"
    ports:
      - "127.0.0.1:9126:9126"
  mongodb3:
    image: mongo:8@sha256:e0ce8c35124d4a9f9785532d1f268f39e9728ffa1cb38f46fa482436424c4bd3
    ports:
      - "27018:27017"
  mongodb:
    image: mongo:8@sha256:e0ce8c35124d4a9f9785532d1f268f39e9728ffa1cb38f46fa482436424c4bd3
    ports:
      - "27017:27017"
  memcached:
    image: memcached:1.6-alpine@sha256:c29847751abb41f4c268c84fb3087fee05d4edcbda44409ccb5086e26148e8a7
    ports:
      - "11211:11211"
  kafka:
    image: confluentinc/confluent-local:8.3.1@sha256:1e333105535e20a573d5d99048de4bdb484017e0a63b660dcbba3925208195f4
    container_name: kafka
    environment:
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9093,BROKER://0.0.0.0:9092,CONTROLLER://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9093,BROKER://localhost:9092"
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://0.0.0.0:9093,BROKER://0.0.0.0:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "BROKER"
      KAFKA_BROKER_ID: "1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    ports:
      - "9092:9092"
      - "9093:9093"
  localstack:
    image: localstack/localstack:4.14.0@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a
    ports:
      - "4566:4566"
