// Code generated by gencontribs. DO NOT EDIT.
// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2016 Datadog, Inc.

package stacktrace

// Code generated by github.com/DataDog/dd-trace-go/scripts/gencontribs DO NOT EDIT.

// generatedThirdPartyLibraries returns the list of third-party libraries
// automatically extracted from all contrib module dependencies.
//
// This list is generated at build time by traversing all contrib directories
// and running 'go list -m all' in each to capture all dependencies.
func generatedThirdPartyLibraries() []string {
	return []string{
		"github.com/yosida95/uritemplate/v3",
	}
}
