# Stage 1: Prepare the library
FROM alpine:latest

# Build arguments for the final archive names; you can override these during build
ARG FILE_NAME=libcivisibility

# Install p7zip for compression
RUN apk add --no-cache p7zip

WORKDIR /app
# Copy everything from the current directory to the PWD (Present Working Directory) inside the container
COPY . .

# Create the output folder
RUN mkdir -p /output

# Compress both files into a 7z archive
RUN 7z a /output/${FILE_NAME}-static.7z /app/output/windows-x64-libtestoptimization-static/*.*
RUN 7z a /output/${FILE_NAME}-dynamic.7z /app/output/windows-x64-libtestoptimization-dynamic/*.*
# Create a SHA256 checksum file for the archive
RUN sha256sum /output/${FILE_NAME}-static.7z > /output/${FILE_NAME}-static.7z.sha256sum
RUN sha256sum /output/${FILE_NAME}-dynamic.7z > /output/${FILE_NAME}-dynamic.7z.sha256sum

# Command to run when the container starts
ENTRYPOINT ["sh", "-c", "ls /output && cp /output/*.* /libtestoptimization && rm -r /libtestoptimization/windows-x64-libtestoptimization-static /libtestoptimization/windows-x64-libtestoptimization-dynamic && echo 'Static library copied.'"]
