body:
  - type: input
    attributes:
      label: Package Name
      description: "If your feature request is to add instrumentation support for a package please provide the name here"
      placeholder: doctrine/orm
    validations:
      required: false

  - type: input
    attributes:
      label: Package Version(s)
      description: "If your feature request is to add instrumentation support for a package please provide the version you use"
      placeholder: 3.3.0
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: |
        Please add a clear and concise description of your problem.
        E.g. I'm unable to instrument my database queries...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
    validations:
      required: false
