// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/traceprof/testapp/test_app.proto

package testapp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorkReq struct {
	CpuDuration          int64    `protobuf:"varint,1,opt,name=cpu_duration,json=cpuDuration,proto3" json:"cpu_duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkReq) Reset()         { *m = WorkReq{} }
func (m *WorkReq) String() string { return proto.CompactTextString(m) }
func (*WorkReq) ProtoMessage()    {}
func (*WorkReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_519e69f486aea913, []int{0}
}

func (m *WorkReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkReq.Unmarshal(m, b)
}
func (m *WorkReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkReq.Marshal(b, m, deterministic)
}
func (m *WorkReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkReq.Merge(m, src)
}
func (m *WorkReq) XXX_Size() int {
	return xxx_messageInfo_WorkReq.Size(m)
}
func (m *WorkReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkReq.DiscardUnknown(m)
}

var xxx_messageInfo_WorkReq proto.InternalMessageInfo

func (m *WorkReq) GetCpuDuration() int64 {
	if m != nil {
		return m.CpuDuration
	}
	return 0
}

type WorkRes struct {
	SpanId               string   `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	LocalRootSpanId      string   `protobuf:"bytes,2,opt,name=local_root_span_id,json=localRootSpanId,proto3" json:"local_root_span_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkRes) Reset()         { *m = WorkRes{} }
func (m *WorkRes) String() string { return proto.CompactTextString(m) }
func (*WorkRes) ProtoMessage()    {}
func (*WorkRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_519e69f486aea913, []int{1}
}

func (m *WorkRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkRes.Unmarshal(m, b)
}
func (m *WorkRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkRes.Marshal(b, m, deterministic)
}
func (m *WorkRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkRes.Merge(m, src)
}
func (m *WorkRes) XXX_Size() int {
	return xxx_messageInfo_WorkRes.Size(m)
}
func (m *WorkRes) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkRes.DiscardUnknown(m)
}

var xxx_messageInfo_WorkRes proto.InternalMessageInfo

func (m *WorkRes) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

func (m *WorkRes) GetLocalRootSpanId() string {
	if m != nil {
		return m.LocalRootSpanId
	}
	return ""
}

func init() {
	proto.RegisterType((*WorkReq)(nil), "testapp.WorkReq")
	proto.RegisterType((*WorkRes)(nil), "testapp.WorkRes")
}

func init() {
	proto.RegisterFile("internal/traceprof/testapp/test_app.proto", fileDescriptor_519e69f486aea913)
}

var fileDescriptor_519e69f486aea913 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x85, 0x3d, 0x95, 0x5b, 0x8c, 0x82, 0x92, 0x46, 0xb1, 0xd2, 0xad, 0x14, 0xef, 0x12, 0xd4,
	0x42, 0x10, 0x1b, 0x65, 0x1b, 0x2b, 0x61, 0x15, 0x04, 0x9b, 0x30, 0x6e, 0x62, 0x08, 0xb7, 0x64,
	0xc6, 0x64, 0xd6, 0xdf, 0x2f, 0x17, 0x72, 0x8d, 0x60, 0x15, 0xf2, 0xcd, 0xc7, 0xf0, 0xe6, 0x89,
	0xcb, 0x10, 0xd9, 0xa5, 0x08, 0xa3, 0xe6, 0x04, 0x83, 0xa3, 0x84, 0x5f, 0x9a, 0x5d, 0x66, 0x20,
	0x2a, 0xaf, 0x01, 0x22, 0x45, 0x09, 0x19, 0x65, 0x53, 0x79, 0xbb, 0x10, 0xcd, 0x3b, 0xa6, 0x55,
	0xef, 0xbe, 0xe5, 0xb9, 0x38, 0x18, 0x68, 0x32, 0x76, 0x4a, 0xc0, 0x01, 0xe3, 0xc9, 0xec, 0x6c,
	0x76, 0xb1, 0xd3, 0xef, 0x0f, 0x34, 0x75, 0x15, 0xb5, 0x2f, 0x1b, 0x3b, 0xcb, 0x63, 0xd1, 0x64,
	0x82, 0x68, 0x82, 0x2d, 0xe2, 0x5e, 0x3f, 0x5f, 0x7f, 0x9f, 0xad, 0xbc, 0x12, 0x72, 0xc4, 0x01,
	0x46, 0x93, 0x10, 0xd9, 0x6c, 0x9c, 0xed, 0xe2, 0x1c, 0x96, 0x49, 0x8f, 0xc8, 0xaf, 0x45, 0xbe,
	0xb9, 0x13, 0xcd, 0x9b, 0xcb, 0xfc, 0x48, 0x24, 0x17, 0x62, 0x77, 0xbd, 0x5b, 0x1e, 0xa9, 0x9a,
	0x4d, 0xd5, 0x60, 0xa7, 0x7f, 0x49, 0x6e, 0xb7, 0x9e, 0x1e, 0x3e, 0xee, 0x3d, 0xd2, 0xca, 0xab,
	0x10, 0x75, 0x07, 0x0c, 0x1d, 0x7a, 0x6d, 0xed, 0xb2, 0x1c, 0xbe, 0xf4, 0xa8, 0x7e, 0xae, 0xf5,
	0xff, 0x6d, 0x7c, 0xce, 0x4b, 0x0b, 0xb7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x4d, 0x85,
	0x45, 0x32, 0x01, 0x00, 0x00,
}
