//
//Run this generate Go code after changing things below:
//
//protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative internal/traceprof/testapp/test_app.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: internal/traceprof/testapp/test_app.proto

package testapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuDuration int64 `protobuf:"varint,1,opt,name=cpu_duration,json=cpuDuration,proto3" json:"cpu_duration,omitempty"`
	SqlDuration int64 `protobuf:"varint,2,opt,name=sql_duration,json=sqlDuration,proto3" json:"sql_duration,omitempty"`
}

func (x *WorkReq) Reset() {
	*x = WorkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_traceprof_testapp_test_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkReq) ProtoMessage() {}

func (x *WorkReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_traceprof_testapp_test_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkReq.ProtoReflect.Descriptor instead.
func (*WorkReq) Descriptor() ([]byte, []int) {
	return file_internal_traceprof_testapp_test_app_proto_rawDescGZIP(), []int{0}
}

func (x *WorkReq) GetCpuDuration() int64 {
	if x != nil {
		return x.CpuDuration
	}
	return 0
}

func (x *WorkReq) GetSqlDuration() int64 {
	if x != nil {
		return x.SqlDuration
	}
	return 0
}

type WorkRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpanId          string `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	LocalRootSpanId string `protobuf:"bytes,2,opt,name=local_root_span_id,json=localRootSpanId,proto3" json:"local_root_span_id,omitempty"`
}

func (x *WorkRes) Reset() {
	*x = WorkRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_traceprof_testapp_test_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRes) ProtoMessage() {}

func (x *WorkRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_traceprof_testapp_test_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRes.ProtoReflect.Descriptor instead.
func (*WorkRes) Descriptor() ([]byte, []int) {
	return file_internal_traceprof_testapp_test_app_proto_rawDescGZIP(), []int{1}
}

func (x *WorkRes) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *WorkRes) GetLocalRootSpanId() string {
	if x != nil {
		return x.LocalRootSpanId
	}
	return ""
}

var File_internal_traceprof_testapp_test_app_proto protoreflect.FileDescriptor

var file_internal_traceprof_testapp_test_app_proto_rawDesc = []byte{
	0x0a, 0x29, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x65,
	0x70, 0x72, 0x6f, 0x66, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x61, 0x70, 0x70, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x5f, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x70, 0x22, 0x4f, 0x0a, 0x07, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x70, 0x75, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x70, 0x75, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x71, 0x6c, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x71, 0x6c, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x07, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x70, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x12, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x73, 0x70, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x52, 0x6f, 0x6f, 0x74,
	0x53, 0x70, 0x61, 0x6e, 0x49, 0x64, 0x32, 0x37, 0x0a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x41, 0x70,
	0x70, 0x12, 0x2c, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x10, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x61, 0x70, 0x70, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x61, 0x70, 0x70, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42,
	0x3c, 0x5a, 0x3a, 0x67, 0x6f, 0x70, 0x6b, 0x67, 0x2e, 0x69, 0x6e, 0x2f, 0x44, 0x61, 0x74, 0x61,
	0x44, 0x6f, 0x67, 0x2f, 0x64, 0x64, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2d, 0x67, 0x6f, 0x2e,
	0x76, 0x31, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x63,
	0x65, 0x70, 0x72, 0x6f, 0x66, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x61, 0x70, 0x70, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_traceprof_testapp_test_app_proto_rawDescOnce sync.Once
	file_internal_traceprof_testapp_test_app_proto_rawDescData = file_internal_traceprof_testapp_test_app_proto_rawDesc
)

func file_internal_traceprof_testapp_test_app_proto_rawDescGZIP() []byte {
	file_internal_traceprof_testapp_test_app_proto_rawDescOnce.Do(func() {
		file_internal_traceprof_testapp_test_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_traceprof_testapp_test_app_proto_rawDescData)
	})
	return file_internal_traceprof_testapp_test_app_proto_rawDescData
}

var file_internal_traceprof_testapp_test_app_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_traceprof_testapp_test_app_proto_goTypes = []interface{}{
	(*WorkReq)(nil), // 0: testapp.WorkReq
	(*WorkRes)(nil), // 1: testapp.WorkRes
}
var file_internal_traceprof_testapp_test_app_proto_depIdxs = []int32{
	0, // 0: testapp.TestApp.Work:input_type -> testapp.WorkReq
	1, // 1: testapp.TestApp.Work:output_type -> testapp.WorkRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_traceprof_testapp_test_app_proto_init() }
func file_internal_traceprof_testapp_test_app_proto_init() {
	if File_internal_traceprof_testapp_test_app_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_traceprof_testapp_test_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_traceprof_testapp_test_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_traceprof_testapp_test_app_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_traceprof_testapp_test_app_proto_goTypes,
		DependencyIndexes: file_internal_traceprof_testapp_test_app_proto_depIdxs,
		MessageInfos:      file_internal_traceprof_testapp_test_app_proto_msgTypes,
	}.Build()
	File_internal_traceprof_testapp_test_app_proto = out.File
	file_internal_traceprof_testapp_test_app_proto_rawDesc = nil
	file_internal_traceprof_testapp_test_app_proto_goTypes = nil
	file_internal_traceprof_testapp_test_app_proto_depIdxs = nil
}
