// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2026 Datadog, Inc.

// Package connect provides tracing for connectrpc.com/connect clients and handlers.
//
// The interceptors created by NewInterceptor, NewClientInterceptor and NewServerInterceptor start
// a "connect.client" or "connect.server" span for every RPC and, for streaming RPCs, a
// "connect.message" span for every message sent or received (see WithStreamCalls and
// WithStreamMessages). The rpc.system tag is "connectrpc" for the Connect protocol and "grpc" for
// both gRPC and gRPC-Web.
//
// A client stream's call span finishes once the stream has reached a terminal state and no other
// stream method is still running. The terminal states are CloseResponse, any Receive error
// (including io.EOF), a CloseRequest error, a Send error other than io.EOF (after which Receive
// reports the server's error), a panic in a stream method, and the end of the stream's context.
// Close or drain client streams as connect requires, or their spans are never finished.
//
// Finished message spans are held in memory until their call span finishes, and the tracer drops
// traces of more than 100,000 spans. For streams with many messages, use WithStreamMessages(false)
// or enable partial flushing (DD_TRACE_PARTIAL_FLUSH_ENABLED).
//
// With Orchestrion, handlers built with connect's handler constructors and clients configured
// through connect.WithClientOptions are instrumented automatically. Clients generated by
// protoc-gen-connect-go v1.13.0 or later always use connect.WithClientOptions; older generators
// emit it only for methods with an idempotency_level option, or not at all.
package connect // import "github.com/DataDog/dd-trace-go/contrib/connectrpc.com/connect/v2"

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"reflect"
	"strconv"
	"strings"

	connectrpc "connectrpc.com/connect"

	"github.com/DataDog/dd-trace-go/v2/ddtrace/ext"
	"github.com/DataDog/dd-trace-go/v2/ddtrace/tracer"
	"github.com/DataDog/dd-trace-go/v2/instrumentation"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	operationClient  = "connect.client"
	operationServer  = "connect.server"
	operationMessage = "connect.message"

	tagMethodKind            = "connect.method.kind"
	tagConnectErrorCode      = "rpc.connect_rpc.error_code"
	tagGRPCStatusCode        = "rpc.grpc.status_code"
	tagConnectRequest        = "connect.request"
	tagGRPCRequest           = "grpc.request"
	tagRequestMetadataPrefix = "rpc.request.metadata."

	methodKindUnary        = "unary"
	methodKindClientStream = "client_streaming"
	methodKindServerStream = "server_streaming"
	methodKindBidiStream   = "bidi_streaming"
	methodKindUnknown      = "unknown"
)

// notModifiedStatus is the http.status_code of a not-modified response; like other HTTP
// integrations, it is a string.
var notModifiedStatus = strconv.Itoa(http.StatusNotModified)

var instr *instrumentation.Instrumentation

func init() {
	instr = instrumentation.Load(instrumentation.PackageConnectRPC)
}

// NewInterceptor returns an interceptor that traces both clients and handlers.
func NewInterceptor(opts ...Option) connectrpc.Interceptor {
	return newInterceptor(true, true, opts...)
}

// NewClientInterceptor returns an interceptor that traces clients.
func NewClientInterceptor(opts ...Option) connectrpc.Interceptor {
	return newInterceptor(true, false, opts...)
}

// NewServerInterceptor returns an interceptor that traces handlers.
func NewServerInterceptor(opts ...Option) connectrpc.Interceptor {
	return newInterceptor(false, true, opts...)
}

type interceptor struct {
	cfg         *config
	traceClient bool
	traceServer bool
}

func newInterceptor(traceClient, traceServer bool, opts ...Option) *interceptor {
	cfg := newConfig(opts...)
	instr.Logger().Debug("contrib/connectrpc.com/connect: configuring interceptor: %#v", cfg)
	return &interceptor{cfg: cfg, traceClient: traceClient, traceServer: traceServer}
}

func (i *interceptor) WrapUnary(next connectrpc.UnaryFunc) connectrpc.UnaryFunc {
	return func(ctx context.Context, request connectrpc.AnyRequest) (connectrpc.AnyResponse, error) {
		spec := request.Spec()
		if spec.IsClient {
			if !i.traceClient {
				return next(ctx, request)
			}
			ctx, traced := i.cfg.claimCall(ctx, spec.Procedure, clientCallKey{}, request)
			if !traced {
				return next(ctx, request)
			}
			return i.cfg.traceUnaryClient(ctx, spec, request, next)
		}
		if !i.traceServer {
			return next(ctx, request)
		}
		ctx, traced := i.cfg.claimCall(ctx, spec.Procedure, serverCallKey{}, request)
		if !traced {
			return next(ctx, request)
		}
		return i.cfg.traceUnaryHandler(ctx, spec, request, next)
	}
}

func (i *interceptor) WrapStreamingClient(next connectrpc.StreamingClientFunc) connectrpc.StreamingClientFunc {
	if !i.traceClient {
		return next
	}
	return func(ctx context.Context, spec connectrpc.Spec) connectrpc.StreamingClientConn {
		ctx, traced := i.cfg.claimCall(ctx, spec.Procedure, clientCallKey{}, nil)
		if !traced {
			conn := next(ctx, spec)
			// Streams have no per-call identity, so a stream to the same procedure opened through
			// another client within a traced call is passed through too: keep it in the trace.
			if marker := handledCall(ctx, clientCallKey{}, spec.Procedure, nil); marker != nil && marker.traced {
				injectSpan(ctx, conn.RequestHeader())
			}
			return conn
		}
		return i.cfg.traceStreamingClient(ctx, spec, next)
	}
}

func (i *interceptor) WrapStreamingHandler(next connectrpc.StreamingHandlerFunc) connectrpc.StreamingHandlerFunc {
	if !i.traceServer {
		return next
	}
	return func(ctx context.Context, conn connectrpc.StreamingHandlerConn) error {
		spec := conn.Spec()
		ctx, traced := i.cfg.claimCall(ctx, spec.Procedure, serverCallKey{}, nil)
		if !traced {
			return next(ctx, conn)
		}
		return i.cfg.traceStreamingHandler(ctx, spec, conn, next)
	}
}

// claimCall reports whether to trace a call to procedure on the side identified by key; request is
// nil for streams. It does not if an outer interceptor on that side already handles the call, or if
// procedure is untraced: the returned context is then marked so that inner interceptors leave the
// call untraced too.
func (cfg *config) claimCall(ctx context.Context, procedure string, key any, request connectrpc.AnyRequest) (context.Context, bool) {
	if handledCall(ctx, key, procedure, request) != nil {
		return ctx, false
	}
	if _, untraced := cfg.untracedMethods[procedure]; untraced {
		return markHandled(ctx, key, callMarker{procedure: procedure, request: request}), false
	}
	return ctx, true
}

type (
	clientCallKey struct{}
	serverCallKey struct{}
)

// callMarker identifies a call that an interceptor handles, with or without a call span, so that
// inner interceptors on the same side don't trace it again.
type callMarker struct {
	procedure string
	// request is the unary request, which every interceptor of one chain shares; nil for streams.
	request connectrpc.AnyRequest
	// span is the call span, or the span that was active when the call was handled without one.
	span *tracer.Span
	// traced is false for untraced procedures.
	traced bool
}

// markHandled marks ctx as handling the call described by marker on the side identified by key.
// A nil marker.span is replaced with the active span.
func markHandled(ctx context.Context, key any, marker callMarker) context.Context {
	if marker.span == nil {
		marker.span, _ = tracer.SpanFromContext(ctx)
	}
	return context.WithValue(ctx, key, &marker)
}

// handledCall returns the marker of an outer interceptor on the same side that handles this call:
// same procedure, same unary request, and the span it recorded is still active. Per-side keys keep
// servers whose context derives from an in-memory client's traced.
func handledCall(ctx context.Context, key any, procedure string, request connectrpc.AnyRequest) *callMarker {
	marker, ok := ctx.Value(key).(*callMarker)
	if !ok || marker.procedure != procedure || !sameRequest(marker.request, request) {
		return nil
	}
	if active, _ := tracer.SpanFromContext(ctx); active != marker.span {
		return nil
	}
	return marker
}

// sameRequest reports whether a and b are the same unary request, or both nil. connect's requests
// are pointers; other dynamic types are never considered equal, since comparing them could panic.
func sameRequest(a, b connectrpc.AnyRequest) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	return reflect.ValueOf(a).Kind() == reflect.Pointer && a == b
}

// protocolTags holds every protocol-dependent tag decision.
type protocolTags struct {
	system              string
	grpcStatus          bool // numeric status tag always set; rpc.grpc.full_method set
	statusCodeTag       string
	requestTag          string
	statusDetailsPrefix string
	notModifiedEligible bool
}

var (
	connectProtocol = protocolTags{
		system:              ext.RPCSystemConnectRPC,
		statusCodeTag:       tagConnectErrorCode,
		requestTag:          tagConnectRequest,
		statusDetailsPrefix: "connect.status_details.",
		notModifiedEligible: true,
	}
	grpcProtocol = protocolTags{
		system:              ext.RPCSystemGRPC,
		grpcStatus:          true,
		statusCodeTag:       tagGRPCStatusCode,
		requestTag:          tagGRPCRequest,
		statusDetailsPrefix: "grpc.status_details.",
	}
)

// protocolTagsFor maps gRPC and gRPC-Web to the gRPC tags, and every other protocol, including an
// unknown or empty one, to the Connect tags.
func protocolTagsFor(protocol string) *protocolTags {
	switch protocol {
	case connectrpc.ProtocolGRPC, connectrpc.ProtocolGRPCWeb:
		return &grpcProtocol
	default:
		return &connectProtocol
	}
}

// spanBases holds one side's (client or server) read-only span configuration.
type spanBases struct {
	callOperation string
	callKey       any
	spanKind      string
	call          *tracer.StartSpanConfig
	message       *tracer.StartSpanConfig
	callOpt       tracer.StartSpanOption
	messageOpt    tracer.StartSpanOption
}

func newSpanBases(component instrumentation.Component, analyticsRate float64) spanBases {
	b := spanBases{callOperation: operationServer, callKey: serverCallKey{}, spanKind: ext.SpanKindServer}
	if component == instrumentation.ComponentClient {
		b.callOperation, b.callKey, b.spanKind = operationClient, clientCallKey{}, ext.SpanKindClient
	}
	spanType := tracer.SpanType(ext.AppTypeRPC)
	componentTag := tracer.Tag(ext.Component, string(instrumentation.PackageConnectRPC))
	analytics := tracer.AnalyticsRate(analyticsRate)
	b.call = tracer.NewStartSpanConfig(spanType, componentTag, analytics, tracer.Tag(ext.SpanKind, b.spanKind), tracer.Measured())
	if component == instrumentation.ComponentServer {
		// Like contrib/google.golang.org/grpc, server message latency counts toward trace stats.
		b.message = tracer.NewStartSpanConfig(spanType, componentTag, analytics, tracer.Measured())
	} else {
		b.message = tracer.NewStartSpanConfig(spanType, componentTag, analytics)
	}
	b.callOpt = tracer.WithStartSpanConfig(b.call)
	b.messageOpt = tracer.WithStartSpanConfig(b.message)
	return b
}

func (cfg *config) bases(component instrumentation.Component) *spanBases {
	if component == instrumentation.ComponentClient {
		return &cfg.client
	}
	return &cfg.server
}

// appendSpanOptions appends span start options in a load-bearing order. The dynamic WithTags must
// precede the cached base, which would otherwise alias and later mutate the base's tag map.
// Extracted parents precede WithSpanOptions so a user parent wins, and custom tags go last.
func (cfg *config) appendSpanOptions(opts []tracer.StartSpanOption, dynamic tracer.StartSpanOption, parentOpts []tracer.StartSpanOption, base, service tracer.StartSpanOption) []tracer.StartSpanOption {
	opts = append(opts, dynamic)
	opts = append(opts, parentOpts...)
	opts = append(opts, base)
	if service != nil {
		opts = append(opts, service)
	}
	if len(cfg.spanOpts) == 0 && cfg.customTags == nil {
		return opts
	}
	opts = append(opts, cfg.spanOpts...)
	if cfg.customTags != nil {
		opts = append(opts, cfg.customTags)
	}
	return append(opts, preferUserService)
}

// preferUserService drops the interceptor's service when a user option sets ext.ServiceName: both
// set the span's service, and the tracer applies start tags in random map order.
func preferUserService(cfg *tracer.StartSpanConfig) {
	if _, ok := cfg.Tags[ext.ServiceName]; ok {
		delete(cfg.Tags, ext.KeyServiceSource)
	}
}

// startCallSpan starts a call span with the dynamic tags and marks ctx as handling the call for its
// side; request is nil for streams. Call spans always get the service option, even an empty one, so
// they don't inherit the service of a parent such as an HTTP server span.
func (cfg *config) startCallSpan(ctx context.Context, component instrumentation.Component, procedure string, request connectrpc.AnyRequest, tags map[string]any, parentOpts ...tracer.StartSpanOption) (*tracer.Span, context.Context) {
	bases := cfg.bases(component)
	var buf [8]tracer.StartSpanOption
	opts := cfg.appendSpanOptions(buf[:0], tracer.WithTags(tags), parentOpts, bases.callOpt, cfg.resolveService().opt)
	span, ctx := tracer.StartSpanFromContext(ctx, bases.callOperation, opts...)
	return span, markHandled(ctx, bases.callKey, callMarker{procedure: procedure, request: request, span: span, traced: true})
}

// messageTags returns the dynamic tags shared by every message span of a stream.
func messageTags(spec connectrpc.Spec, protocol *protocolTags) tracer.StartSpanOption {
	tags := make(map[string]any, 6)
	addProcedureTags(tags, spec)
	addProtocolTags(tags, protocol, spec.Procedure)
	return tracer.WithTags(tags)
}

// startMessageSpan starts a message span. Root-ness is checked on the started span because
// WithSpanOptions may set a parent; callers must not share an extracted parent between message
// spans, since the tracer backfills it the first time it parents a span. An empty service is
// skipped, as the tracer would then mark the span top-level before defaulting its service, except
// on server message spans without a call span: like call spans, they must not inherit the service
// of a local parent such as an HTTP server span.
func (cfg *config) startMessageSpan(ctx context.Context, tags tracer.StartSpanOption, component instrumentation.Component, parentOpts ...tracer.StartSpanOption) *tracer.Span {
	bases := cfg.bases(component)
	var service tracer.StartSpanOption
	if svc := cfg.resolveService(); svc.name != "" || (component == instrumentation.ComponentServer && !cfg.traceStreamCalls) {
		service = svc.opt
	}
	var buf [8]tracer.StartSpanOption
	span, _ := tracer.StartSpanFromContext(ctx, operationMessage, cfg.appendSpanOptions(buf[:0], tags, parentOpts, bases.messageOpt, service)...)
	if span.Root() == span {
		span.SetTag(ext.SpanKind, bases.spanKind)
	}
	return span
}

func addProcedureTags(tags map[string]any, spec connectrpc.Spec) {
	service, method := parseProcedure(spec.Procedure)
	tags[ext.ResourceName] = spec.Procedure
	tags[ext.RPCService] = service
	tags[ext.RPCMethod] = method
	tags[tagMethodKind] = methodKind(spec.StreamType)
}

func addProtocolTags(tags map[string]any, protocol *protocolTags, procedure string) {
	tags[ext.RPCSystem] = protocol.system
	if protocol.grpcStatus {
		tags[ext.GRPCFullMethod] = procedure
	}
}

func setProtocolTags(span *tracer.Span, protocol *protocolTags, procedure string) {
	span.SetTag(ext.RPCSystem, protocol.system)
	if protocol.grpcStatus {
		span.SetTag(ext.GRPCFullMethod, procedure)
	}
}

func parseProcedure(procedure string) (service, method string) {
	service, method, _ = strings.Cut(strings.TrimPrefix(procedure, "/"), "/")
	return service, method
}

func methodKind(streamType connectrpc.StreamType) string {
	switch streamType {
	case connectrpc.StreamTypeUnary:
		return methodKindUnary
	case connectrpc.StreamTypeClient:
		return methodKindClientStream
	case connectrpc.StreamTypeServer:
		return methodKindServerStream
	case connectrpc.StreamTypeBidi:
		return methodKindBidiStream
	default:
		return methodKindUnknown
	}
}

func codeOf(err error) connectrpc.Code {
	if connectErr, ok := errors.AsType[*connectrpc.Error](err); ok {
		// Every method of a nil *connectrpc.Error dereferences it, including Unwrap, which
		// errors.Is below would reach.
		if connectErr == nil {
			return connectrpc.CodeUnknown
		}
		return connectErr.Code()
	}
	switch {
	case errors.Is(err, context.Canceled):
		return connectrpc.CodeCanceled
	case errors.Is(err, context.DeadlineExceeded):
		return connectrpc.CodeDeadlineExceeded
	default:
		return connectrpc.CodeOf(err)
	}
}

// isExpectedStreamEOF reports whether err is connect's normal end-of-stream signal: io.EOF, which
// connect wraps with CodeUnknown. An EOF with any other explicit code is a real error.
func isExpectedStreamEOF(err error) bool {
	if err == nil || !isSafeToInspect(err) {
		return false
	}
	return codeOf(err) == connectrpc.CodeUnknown && errors.Is(err, io.EOF)
}

// isUncodedCancellation reports whether err is a context cancellation without an explicit
// connect code, which is never recorded as an error.
func isUncodedCancellation(err error) bool {
	if _, coded := errors.AsType[*connectrpc.Error](err); coded {
		return false
	}
	return errors.Is(err, context.Canceled)
}

// isSuppressedTerminalError applies only the code-based rules of finishOutcomeFor, never
// cfg.errCheck, so client streams can compare terminal error candidates without calling it.
func isSuppressedTerminalError(err error, cfg *config) bool {
	return err == nil || isUncodedCancellation(err) || cfg.nonErrorCodes[codeOf(err)]
}

// normalizeError replaces an error that is unsafe to inspect with one that is safe. The methods of
// a nil error, or of a nil *connectrpc.Error in its chain, panic, and so may walking a chain whose
// Unwrap, Is or As methods dereference a nil receiver.
func normalizeError(err error) error {
	if err == nil || isSafeToInspect(err) {
		return err
	}
	return fmt.Errorf("connect: error value (%T) is unsafe to inspect: it is nil, has a nil *connectrpc.Error in its chain, or panics when unwrapped", err)
}

func isSafeToInspect(err error) (safe bool) {
	defer func() {
		if recover() != nil {
			safe = false
		}
	}()
	if isNilError(err) || hasNilConnectError(err) {
		return false
	}
	// A target that never matches makes errors.Is call every Unwrap and Is method in the chain.
	_ = errors.Is(err, errInspectionProbe)
	return true
}

var errInspectionProbe = errors.New("connect: error inspection probe")

// finishMode selects which outcomes finishSpan treats as non-errors.
type finishMode struct {
	allowEOF         bool // connect's end-of-stream signal is not an error
	allowNotModified bool // a not-modified response is a 304, not an error
	isPanic          bool // the error is always recorded
}

var messageFinishMode = finishMode{allowEOF: true}

func unaryFinishMode(protocol *protocolTags, httpMethod string) finishMode {
	return finishMode{allowNotModified: protocol.notModifiedEligible && httpMethod == http.MethodGet}
}

type finishOutcome struct {
	code        connectrpc.Code
	expectedEOF bool
	notModified bool
	recorded    error // the error to record on the span, if any
}

// finishOutcomeFor classifies a normalized, non-panic err.
func finishOutcomeFor(err error, procedure string, mode finishMode, cfg *config) finishOutcome {
	if err == nil {
		return finishOutcome{}
	}
	out := finishOutcome{
		code:        codeOf(err),
		expectedEOF: mode.allowEOF && isExpectedStreamEOF(err),
		notModified: mode.allowNotModified && connectrpc.IsNotModifiedError(err),
	}
	switch {
	case out.expectedEOF, out.notModified, isUncodedCancellation(err), cfg.nonErrorCodes[out.code]:
	case cfg.errCheck != nil && !cfg.errCheck(procedure, err):
	default:
		out.recorded = err
	}
	return out
}

// finishSpan finishes span with err. A panic is always recorded, even when its value would
// otherwise be suppressed, because it is re-raised and must stay visible in the trace.
func finishSpan(span *tracer.Span, err error, procedure string, protocol *protocolTags, mode finishMode, cfg *config) {
	if span == nil {
		return
	}
	err = normalizeError(err)
	var out finishOutcome
	if mode.isPanic {
		out = finishOutcome{code: codeOf(err), recorded: err}
	} else {
		out = finishOutcomeFor(err, procedure, mode, cfg)
	}
	finishClassified(span, err, out, protocol, cfg)
}

// finishClassified applies out to a non-nil span. Status tags reflect err even when out suppresses
// it.
func finishClassified(span *tracer.Span, err error, out finishOutcome, protocol *protocolTags, cfg *config) {
	failed := err != nil && !out.expectedEOF
	switch {
	case protocol.grpcStatus:
		var code uint32
		if failed {
			code = uint32(out.code)
		}
		span.SetTag(protocol.statusCodeTag, code)
	case failed && !out.notModified:
		span.SetTag(protocol.statusCodeTag, out.code.String())
	}
	if out.notModified {
		span.SetTag(ext.HTTPCode, notModifiedStatus)
	}
	if out.recorded == nil {
		span.Finish()
		return
	}
	if cfg.withErrorDetailTags {
		setErrorDetailTags(span, out.recorded, protocol)
	}
	if cfg.noDebugStack {
		span.Finish(tracer.WithError(out.recorded), tracer.NoDebugStack())
		return
	}
	span.Finish(tracer.WithError(out.recorded))
}

// spanFinish describes how finishOnReturn classifies a span. Its fields may change until the
// traced function returns.
type spanFinish struct {
	procedure string
	protocol  *protocolTags
	mode      finishMode
}

// finishOnReturn finishes *span with *err, then runs after, if set, with the normalized error. It
// must be deferred directly, because recover only works in the deferred function itself, and reads
// through pointers because the span may start after the defer is registered. A panic, including
// one from cfg.errCheck, still finishes the span and runs after; the original panic value is then
// re-raised.
func (cfg *config) finishOnReturn(span **tracer.Span, err *error, f *spanFinish, after func(err error, isPanic bool)) {
	panicMode := f.mode
	panicMode.isPanic = true
	if recovered := recover(); recovered != nil {
		panicErr := panicError(recovered)
		finishSpan(*span, panicErr, f.procedure, f.protocol, panicMode, cfg)
		if after != nil {
			after(panicErr, true)
		}
		panic(recovered)
	}
	opErr := normalizeError(*err)
	if recovered := recoverFinish(
		func() { finishSpan(*span, opErr, f.procedure, f.protocol, f.mode, cfg) },
		func(panicErr error) { finishSpan(*span, panicErr, f.procedure, f.protocol, panicMode, cfg) },
	); recovered != nil {
		if after != nil {
			after(panicError(recovered), true)
		}
		panic(recovered)
	}
	if after != nil {
		after(opErr, false)
	}
}

// recoverFinish runs finish and, if it panics (e.g. in cfg.errCheck), runs onPanic with the panic
// as an error and returns the recovered value for the caller to re-raise after its own cleanup.
func recoverFinish(finish func(), onPanic func(panicErr error)) (recovered any) {
	defer func() {
		recovered = recover()
		if recovered != nil {
			onPanic(panicError(recovered))
		}
	}()
	finish()
	return nil
}

func panicError(value any) error {
	if err, ok := value.(error); ok && !isNilError(err) {
		return normalizeError(err)
	}
	return fmt.Errorf("panic: %v", value)
}

// isNilError reports whether err is a non-nil interface holding a nil value.
func isNilError(err error) bool {
	v := reflect.ValueOf(err)
	switch v.Kind() {
	case reflect.Pointer, reflect.Map, reflect.Slice, reflect.Chan, reflect.Func, reflect.Interface:
		return v.IsNil()
	default:
		return false
	}
}

// hasNilConnectError reports whether err's chain contains a nil *connectrpc.Error.
func hasNilConnectError(err error) bool {
	connectErr, ok := errors.AsType[*connectrpc.Error](err)
	return ok && connectErr == nil
}

func setErrorDetailTags(span *tracer.Span, err error, protocol *protocolTags) {
	connectErr, ok := errors.AsType[*connectrpc.Error](err)
	if !ok || connectErr == nil {
		return
	}
	for i, detail := range connectErr.Details() {
		message, detailErr := detail.Value()
		if detailErr != nil {
			continue
		}
		span.SetTag(protocol.statusDetailsPrefix+"_"+strconv.Itoa(i), protoimpl.X.MessageStringOf(message))
	}
}

func setMetadataTags(cfg *config, header http.Header, span *tracer.Span) {
	if !cfg.withMetadataTags || span == nil {
		return
	}
	for key, values := range header {
		if key, ok := cfg.metadataKey(key); ok {
			span.SetTag(tagRequestMetadataPrefix+key, values)
		}
	}
}

// metadataKey returns the lowercased header key and whether WithMetadataTags reports it.
func (cfg *config) metadataKey(key string) (string, bool) {
	key = strings.ToLower(key)
	_, ignored := cfg.ignoredMetadata[key]
	return key, !ignored && !strings.HasSuffix(key, "-bin") && !strings.HasPrefix(key, tracer.DefaultBaggageHeaderPrefix)
}

func setRequestTags(cfg *config, request any, protocol *protocolTags, span *tracer.Span) {
	if !cfg.withRequestTags || span == nil {
		return
	}
	message, ok := request.(proto.Message)
	if !ok {
		return
	}
	encoded, err := protojson.Marshal(message)
	if err != nil {
		return
	}
	span.SetTag(protocol.requestTag, string(encoded))
}

func propagationOptions(header http.Header) []tracer.StartSpanOption {
	spanContext, err := tracer.Extract(tracer.HTTPHeadersCarrier(header))
	if err != nil || spanContext == nil {
		return nil
	}
	opts := []tracer.StartSpanOption{tracer.ChildOf(spanContext)}
	if links := spanContext.SpanLinks(); links != nil {
		opts = append(opts, tracer.WithSpanLinks(links))
	}
	return opts
}

func injectSpan(ctx context.Context, header http.Header) {
	span, ok := tracer.SpanFromContext(ctx)
	if !ok {
		return
	}
	if err := tracer.Inject(span.Context(), tracer.HTTPHeadersCarrier(header)); err != nil {
		instr.Logger().Warn("contrib/connectrpc.com/connect: failed to inject trace context: %s", err.Error())
	}
}

// peerTags are the network.destination.* tags of a client's peer. Their values are boxed once, so
// that setting them on every message span of a stream doesn't allocate.
type peerTags struct {
	ip, name, port any
}

func newPeerTags(peer connectrpc.Peer) peerTags {
	host, port, err := net.SplitHostPort(peer.Addr)
	if err != nil {
		host, port = peer.Addr, ""
	}
	var tags peerTags
	host = strings.Trim(host, "[]")
	if ip := net.ParseIP(host); ip != nil {
		tags.ip = ip.String()
	} else if host != "" {
		tags.name = host
	}
	if portNumber, err := strconv.Atoi(port); err == nil {
		tags.port = portNumber
	}
	return tags
}

// set sets the tags after span has started: as start tags, they would overflow the tracer's
// 8-entry small tag map on client message spans.
func (p peerTags) set(span *tracer.Span) {
	if p.ip != nil {
		span.SetTag(ext.NetworkDestinationIP, p.ip)
	}
	if p.name != nil {
		span.SetTag(ext.NetworkDestinationName, p.name)
	}
	if p.port != nil {
		span.SetTag(ext.NetworkDestinationPort, p.port)
	}
}
