// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.
//
// Code generated by 'go generate'; DO NOT EDIT.

package nethttp

import (
	"testing"

	"github.com/DataDog/dd-trace-go/v2/internal/orchestrion/_integration/internal/harness"
)

func TestClientError(t *testing.T) {
	harness.Run(t, new(TestCaseClientError))
}

func TestFuncHandler(t *testing.T) {
	harness.Run(t, new(TestCaseFuncHandler))
}

func TestGlobalFunctions(t *testing.T) {
	harness.Run(t, new(TestCaseGlobalFunctions))
}

func TestHandlerImplementation(t *testing.T) {
	harness.Run(t, new(TestCaseHandlerImplementation))
}

func TestHandlerIsNil(t *testing.T) {
	harness.Run(t, new(TestCaseHandlerIsNil))
}

func TestIssue400(t *testing.T) {
	harness.Run(t, new(TestCaseIssue400))
}

func TestServeMuxHandler(t *testing.T) {
	harness.Run(t, new(TestCaseServeMuxHandler))
}
