// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2024 Datadog, Inc.

// gencontribdoc generates contrib/contrib.go, the package doc for
// github.com/DataDog/dd-trace-go/v2/contrib. It walks contrib/**/go.mod to list every
// published contrib integration module as a doc-comment link, since pkg.go.dev's own
// "Directories" section matches on import-path prefix rather than actual nested-module
// publication and cannot discover contrib/<x>/v2 modules from the .../v2/contrib unit.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// modulePathPrefix is the module path every published contrib integration must have. A few
// go.mod files under contrib/ still carry the old, pre-move prefix
// (github.com/DataDog/dd-trace-go/v2/contrib/...); those were never tagged or published and
// must not be linked here.
const modulePathPrefix = "github.com/DataDog/dd-trace-go/contrib/"

const generatedFileTemplate = `// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2024 Datadog, Inc.

// Code generated by github.com/DataDog/dd-trace-go/scripts/gencontribdoc. DO NOT EDIT.

// The purpose of the packages held in contrib is to provide tracing on top of commonly used
// packages from the standard library as well as the community in a "plug-and-play" manner.
// This means that by simply importing the appropriate path, functions are exposed having
// the same signature as the original package. These functions return structures that embed
// the original return value, allowing them to be used as they normally would with tracing
// activated out of the box.
//
// All of these libraries are supported by our https://www.datadoghq.com/apm/.
//
// # Integrations
//
// Each integration is published as its own module:
{{range .Modules}}//   - [{{.Suffix}}]
{{end -}}
//
{{range .Modules}}// [{{.Suffix}}]: https://pkg.go.dev/{{.Path}}
{{end -}}
package contrib

//go:generate env GOWORK=off go run ../scripts/gencontribdoc/main.go .. contrib.go
`

type contribModule struct {
	// Suffix is the module path with the "github.com/DataDog/dd-trace-go/" prefix trimmed,
	// e.g. "contrib/net/http/v2". Used both as the doc-comment link label and the sort key.
	Suffix string
	// Path is the full module path, used to build the pkg.go.dev URL.
	Path string
}

type templateData struct {
	Modules []contribModule
}

func main() {
	if len(os.Args) != 3 {
		log.Fatal("Usage: gencontribdoc <project-root> <output-file>")
	}

	projectRoot := os.Args[1]
	outputFile := os.Args[2]

	modules, err := findContribModules(projectRoot)
	if err != nil {
		log.Fatalf("Failed to find contrib modules: %v", err)
	}

	if err := generateSourceFile(outputFile, modules); err != nil {
		log.Fatalf("Failed to generate source file: %v", err)
	}

	log.Printf("Generated %s with %d contrib module links", outputFile, len(modules))
}

// findContribModules walks contrib/ for nested modules and returns the ones that belong in
// the package doc: published under modulePathPrefix and not an internal helper module (test
// fixtures, code-generation helpers) that a user would never import directly.
func findContribModules(projectRoot string) ([]contribModule, error) {
	contribDir := filepath.Join(projectRoot, "contrib")

	var modules []contribModule
	err := filepath.WalkDir(contribDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || d.Name() != "go.mod" {
			return nil
		}
		dir := filepath.Dir(path)
		rel, err := filepath.Rel(contribDir, dir)
		if err != nil {
			return fmt.Errorf("computing relative path for %s: %w", dir, err)
		}
		if isExcludedDir(rel) {
			return nil
		}

		modPath, err := readModulePath(dir)
		if err != nil {
			return fmt.Errorf("reading module path in %s: %w", dir, err)
		}
		if !strings.HasPrefix(modPath, modulePathPrefix) {
			return nil
		}

		modules = append(modules, contribModule{
			Suffix: strings.TrimPrefix(modPath, "github.com/DataDog/dd-trace-go/"),
			Path:   modPath,
		})
		return nil
	})
	if err != nil {
		return nil, err
	}

	sort.Slice(modules, func(i, j int) bool { return modules[i].Suffix < modules[j].Suffix })
	return modules, nil
}

// isExcludedDir reports whether dir, a module's directory path relative to contrib/, holds
// an internal helper module rather than a published integration.
func isExcludedDir(dir string) bool {
	for _, part := range strings.Split(filepath.ToSlash(dir), "/") {
		if part == "internal" || part == "testdata" {
			return true
		}
		if strings.HasPrefix(part, "_") || strings.HasPrefix(part, ".") {
			return true
		}
	}
	return false
}

func readModulePath(dir string) (string, error) {
	cmd := exec.Command("go", "mod", "edit", "-json")
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("go mod edit -json: %w", err)
	}

	var parsed struct {
		Module struct {
			Path string
		}
	}
	if err := json.Unmarshal(out, &parsed); err != nil {
		return "", fmt.Errorf("parsing go mod edit -json output: %w", err)
	}
	return parsed.Module.Path, nil
}

func generateSourceFile(outputFile string, modules []contribModule) error {
	tmpl, err := template.New("generated").Parse(generatedFileTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, templateData{Modules: modules}); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format generated code: %w", err)
	}

	return os.WriteFile(outputFile, formatted, 0644)
}
