// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025 Datadog, Inc.

package env

// Code generated by github.com/DataDog/dd-trace-go/v2/scripts/configinverter. DO NOT EDIT.

// SupportedConfigurations is a map of supported configuration keys.
var SupportedConfigurations = map[string]struct{}{
	"DD_TRACE_BAR": {},
	"DD_TRACE_FOO": {},
}
