# This CI jobs are copied from libdatadog-build one-pipeline.yml gitlab template.
variables:
  SCRIPTS_BASE_URL: https://gitlab-templates.ddbuild.io/libdatadog/one-pipeline/ca/a0486057161f85a77e39ad2aa60ac66bb52414696d9b3dd87177df1057b11295/scripts

.download-scripts-from-template: &download-scripts-from-template
  - mkdir -p scripts
  - |
    for script_file in "config-inversion-local-validation.sh" "config-inversion-update-supported-range.sh"
    do
      curl --location --fail --show-error --output "scripts/${script_file}" "${SCRIPTS_BASE_URL}/${script_file}"
      if [[ $script_file == *sh ]]
      then
         chmod +x scripts/$script_file
      fi
    done

.check_config_inversion_local_file:
  allow_failure: false
  rules:
    - when: on_success
  variables:
    LOCAL_JSON_PATH: ""
  before_script:
    - *download-scripts-from-template
  script:
    - scripts/config-inversion-local-validation.sh "$LOCAL_JSON_PATH"

.config_inversion_update_central:
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?[0-9]+\.[0-9]+\.[0-9]+$/'
      when: on_success
  variables:
    LOCAL_JSON_PATH: ""
    LANGUAGE_NAME: ""
    MULTIPLE_RELEASE_LINES: "false" # expect "true" or "false" as a value to determine if a new "branch" identifier is needed to differentiate between multiple release lines
  before_script:
    - *download-scripts-from-template
    - export FP_API_KEY=$(aws ssm get-parameter --region us-east-1 --name ci.$CI_PROJECT_NAME.FP_API_KEY --with-decryption --query "Parameter.Value" --out text)
  script:
    - scripts/config-inversion-update-supported-range.sh "$LOCAL_JSON_PATH" "$LANGUAGE_NAME" "$MULTIPLE_RELEASE_LINES"
