name: 'Setup Go'
description: 'Setup Go and gotestsum for running tests.'
inputs:
  go-version:
    required: true
    description: Go version to setup.
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        cache: false
        check-latest: true

    # We're not using the cache feature provided by setup-go so that we can
    # also cache the gotestsum install below. This can save up to 60s of CI
    # time. It's not entirely clear why the gotestsum install step is slow
    # sometimes, but from my debugging it seems hanging on some Off-CPU,
    # perhaps network activity occasionally.
    - name: Cache go
      id: cache-go
      uses: actions/cache@v3
      with:
        path: |
          /home/runner/.cache/go-build
          /home/runner/go/pkg/mod
          /home/runner/go/bin
        key: ${{ runner.os }}-go-${{ inputs.go-version }}-${{ hashFiles('**/go.mod', '**/go.sum') }}

    - name: Install gotestsum
      if: steps.cache-go.outputs.cache-hit != 'true'
      shell: bash
      run: |
        go install gotest.tools/gotestsum@latest
