name: 'Setup Go'
description: 'Setup Go and Development tools for running tests'
inputs:
  go-version:
    required: true
    description: Go version to setup.
  tools-bin:
    required: true
    description: Directory to installs tools to.
  tools-dir:
    required: true
    description: Directory that has the tool definitions.
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
        check-latest: true

    - name: Cache tools
      id: cache-tools
      uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
      with:
        path: ${{ inputs.tools-bin }}
        key: ${{ runner.os }}-go-${{ inputs.go-version }}-tools-${{ inputs.tools-dir }}-${{ inputs.tools-bin}}-${{ hashFiles('**/go.mod', '**/go.sum') }}

    - name: Install development tools
      if: steps.cache-tools.outputs.cache-hit != 'true'
      shell: bash
      run: |-
        ./scripts/install_tools.sh --tools-dir ${{ inputs.tools-dir }} --bin-dir ${{ inputs.tools-bin }}
