apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-mirror
  namespace: httpbin
  labels:
    app: traffic-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-mirror
  template:
    metadata:
      labels:
        app: traffic-mirror
    spec:
      containers:
        - name: traffic-mirror
          imagePullPolicy: Never
          env:
            - name: DD_TRACE_DEBUG
              value: "true"
            - name: DD_AGENT_HOST
              value: datadog.datadog.svc.cluster.local
          image: traffic-mirror
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: traffic-mirror
  namespace: httpbin
spec:
  selector:
    app: traffic-mirror
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-mirror
  namespace: httpbin
spec:
  parentRefs:
    - name: http
      namespace: kgateway-system
  hostnames:
    - mirror.example
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestMirror
          requestMirror:
            backendRef:
              kind: Service
              name: traffic-mirror
              port: 8080
      backendRefs:
        - name: httpbin
          port: 8000
