apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-filter-mirror
spec:
  parentRefs:
    - name: mirror-gateway
  hostnames:
    - mirror.example
  rules:
    - backendRefs:
        - name: foo-v1
          port: 8080
