// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023 Datadog, Inc.

// Code generated by 'go run gopkg.in/DataDog/dd-trace-go.v1/dyngo/internal/domainstate/generator' DO NOT EDIT

package domain

import domainstate "gopkg.in/DataDog/dd-trace-go.v1/dyngo/internal/domainstate"

//go:generate go run gopkg.in/DataDog/dd-trace-go.v1/dyngo/internal/domainstate/generator

type Domain = domainstate.Domain

const (
	GRPC        = domainstate.GRPC
	GraphQL     = domainstate.GraphQL
	HTTP        = domainstate.HTTP
	Performance = domainstate.Performance
)
