// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025 Datadog, Inc.

package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"

	"github.com/DataDog/dd-trace-go/contrib/99designs/gqlgen/v2/internal/testserver/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// WithError is the resolver for the withError field.
func (r *queryResolver) WithError(ctx context.Context) (*string, error) {
	return nil, &gqlerror.Error{
		Message: "test error",
		Extensions: map[string]any{
			"int":                          1,
			"float":                        1.1,
			"str":                          "1",
			"bool":                         true,
			"slice":                        []string{"1", "2"},
			"unsupported_type_stringified": []any{1, "foo"},
			"not_captured":                 "nope",
		},
	}
}

// TopLevel is the resolver for the topLevel field.
func (r *queryResolver) TopLevel(_ context.Context, id string) (*model.TopLevel, error) {
	return &model.TopLevel{Nested: id}, nil
}

// Nested is the resolver for the nested field.
func (r *topLevelResolver) Nested(_ context.Context, obj *model.TopLevel, id string) (string, error) {
	return fmt.Sprintf("%s/%s", obj.Nested, id), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// TopLevel returns TopLevelResolver implementation.
func (r *Resolver) TopLevel() TopLevelResolver { return &topLevelResolver{r} }

type queryResolver struct{ *Resolver }
type topLevelResolver struct{ *Resolver }
