// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2026 Datadog, Inc.

// Wire-compatible implementation proto for OTEP 4719 ProcessContext.
// This file is used for Go code generation in place of processcontext.proto,
// which cannot be used directly because it imports OTel proto packages that
// conflict with the non-slim OTel packages used elsewhere in this module
// when both end up in the same binary's global proto registry.
// All field numbers match the upstream OTel schema exactly.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: processcontext.proto

package otelprocesscontext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessContext is wire-compatible with opentelemetry.proto.common.v1.ProcessContext.
type ProcessContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Resource        *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	ExtraAttributes []*KeyValue            `protobuf:"bytes,2,rep,name=extra_attributes,json=extraAttributes,proto3" json:"extra_attributes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessContext) Reset() {
	*x = ProcessContext{}
	mi := &file_processcontext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessContext) ProtoMessage() {}

func (x *ProcessContext) ProtoReflect() protoreflect.Message {
	mi := &file_processcontext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessContext.ProtoReflect.Descriptor instead.
func (*ProcessContext) Descriptor() ([]byte, []int) {
	return file_processcontext_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessContext) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ProcessContext) GetExtraAttributes() []*KeyValue {
	if x != nil {
		return x.ExtraAttributes
	}
	return nil
}

// Resource is wire-compatible with opentelemetry.proto.resource.v1.Resource.
type Resource struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Attributes             []*KeyValue            `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	DroppedAttributesCount uint32                 `protobuf:"varint,2,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"dropped_attributes_count,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_processcontext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_processcontext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_processcontext_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetAttributes() []*KeyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Resource) GetDroppedAttributesCount() uint32 {
	if x != nil {
		return x.DroppedAttributesCount
	}
	return 0
}

// KeyValue is wire-compatible with opentelemetry.proto.common.v1.KeyValue.
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *AnyValue              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_processcontext_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_processcontext_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_processcontext_proto_rawDescGZIP(), []int{2}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() *AnyValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// AnyValue is wire-compatible with opentelemetry.proto.common.v1.AnyValue.
type AnyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AnyValue_StringValue
	//	*AnyValue_BoolValue
	//	*AnyValue_IntValue
	//	*AnyValue_DoubleValue
	//	*AnyValue_ArrayValue
	//	*AnyValue_KvlistValue
	//	*AnyValue_BytesValue
	Value         isAnyValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyValue) Reset() {
	*x = AnyValue{}
	mi := &file_processcontext_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyValue) ProtoMessage() {}

func (x *AnyValue) ProtoReflect() protoreflect.Message {
	mi := &file_processcontext_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyValue.ProtoReflect.Descriptor instead.
func (*AnyValue) Descriptor() ([]byte, []int) {
	return file_processcontext_proto_rawDescGZIP(), []int{3}
}

func (x *AnyValue) GetValue() isAnyValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AnyValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AnyValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AnyValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AnyValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *AnyValue) GetArrayValue() *ArrayValue {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *AnyValue) GetKvlistValue() *KeyValueList {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_KvlistValue); ok {
			return x.KvlistValue
		}
	}
	return nil
}

func (x *AnyValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isAnyValue_Value interface {
	isAnyValue_Value()
}

type AnyValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AnyValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AnyValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AnyValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type AnyValue_ArrayValue struct {
	ArrayValue *ArrayValue `protobuf:"bytes,5,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

type AnyValue_KvlistValue struct {
	KvlistValue *KeyValueList `protobuf:"bytes,6,opt,name=kvlist_value,json=kvlistValue,proto3,oneof"`
}

type AnyValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*AnyValue_StringValue) isAnyValue_Value() {}

func (*AnyValue_BoolValue) isAnyValue_Value() {}

func (*AnyValue_IntValue) isAnyValue_Value() {}

func (*AnyValue_DoubleValue) isAnyValue_Value() {}

func (*AnyValue_ArrayValue) isAnyValue_Value() {}

func (*AnyValue_KvlistValue) isAnyValue_Value() {}

func (*AnyValue_BytesValue) isAnyValue_Value() {}

// ArrayValue is wire-compatible with opentelemetry.proto.common.v1.ArrayValue
type ArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AnyValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	mi := &file_processcontext_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_processcontext_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_processcontext_proto_rawDescGZIP(), []int{4}
}

func (x *ArrayValue) GetValues() []*AnyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// KeyValueList is wire-compatible with opentelemetry.proto.common.v1.KeyValueList
type KeyValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*KeyValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueList) Reset() {
	*x = KeyValueList{}
	mi := &file_processcontext_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueList) ProtoMessage() {}

func (x *KeyValueList) ProtoReflect() protoreflect.Message {
	mi := &file_processcontext_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueList.ProtoReflect.Descriptor instead.
func (*KeyValueList) Descriptor() ([]byte, []int) {
	return file_processcontext_proto_rawDescGZIP(), []int{5}
}

func (x *KeyValueList) GetValues() []*KeyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_processcontext_proto protoreflect.FileDescriptor

const file_processcontext_proto_rawDesc = "" +
	"\n" +
	"\x14processcontext.proto\x12\x12otelprocesscontext\"\x93\x01\n" +
	"\x0eProcessContext\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.otelprocesscontext.ResourceR\bresource\x12G\n" +
	"\x10extra_attributes\x18\x02 \x03(\v2\x1c.otelprocesscontext.KeyValueR\x0fextraAttributes\"\x82\x01\n" +
	"\bResource\x12<\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x1c.otelprocesscontext.KeyValueR\n" +
	"attributes\x128\n" +
	"\x18dropped_attributes_count\x18\x02 \x01(\rR\x16droppedAttributesCount\"P\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.otelprocesscontext.AnyValueR\x05value\"\xca\x02\n" +
	"\bAnyValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12A\n" +
	"\varray_value\x18\x05 \x01(\v2\x1e.otelprocesscontext.ArrayValueH\x00R\n" +
	"arrayValue\x12E\n" +
	"\fkvlist_value\x18\x06 \x01(\v2 .otelprocesscontext.KeyValueListH\x00R\vkvlistValue\x12!\n" +
	"\vbytes_value\x18\a \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"B\n" +
	"\n" +
	"ArrayValue\x124\n" +
	"\x06values\x18\x01 \x03(\v2\x1c.otelprocesscontext.AnyValueR\x06values\"D\n" +
	"\fKeyValueList\x124\n" +
	"\x06values\x18\x01 \x03(\v2\x1c.otelprocesscontext.KeyValueR\x06valuesBRZPgithub.com/DataDog/dd-trace-go/v2/internal/otelprocesscontext;otelprocesscontextb\x06proto3"

var (
	file_processcontext_proto_rawDescOnce sync.Once
	file_processcontext_proto_rawDescData []byte
)

func file_processcontext_proto_rawDescGZIP() []byte {
	file_processcontext_proto_rawDescOnce.Do(func() {
		file_processcontext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_processcontext_proto_rawDesc), len(file_processcontext_proto_rawDesc)))
	})
	return file_processcontext_proto_rawDescData
}

var file_processcontext_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_processcontext_proto_goTypes = []any{
	(*ProcessContext)(nil), // 0: otelprocesscontext.ProcessContext
	(*Resource)(nil),       // 1: otelprocesscontext.Resource
	(*KeyValue)(nil),       // 2: otelprocesscontext.KeyValue
	(*AnyValue)(nil),       // 3: otelprocesscontext.AnyValue
	(*ArrayValue)(nil),     // 4: otelprocesscontext.ArrayValue
	(*KeyValueList)(nil),   // 5: otelprocesscontext.KeyValueList
}
var file_processcontext_proto_depIdxs = []int32{
	1, // 0: otelprocesscontext.ProcessContext.resource:type_name -> otelprocesscontext.Resource
	2, // 1: otelprocesscontext.ProcessContext.extra_attributes:type_name -> otelprocesscontext.KeyValue
	2, // 2: otelprocesscontext.Resource.attributes:type_name -> otelprocesscontext.KeyValue
	3, // 3: otelprocesscontext.KeyValue.value:type_name -> otelprocesscontext.AnyValue
	4, // 4: otelprocesscontext.AnyValue.array_value:type_name -> otelprocesscontext.ArrayValue
	5, // 5: otelprocesscontext.AnyValue.kvlist_value:type_name -> otelprocesscontext.KeyValueList
	3, // 6: otelprocesscontext.ArrayValue.values:type_name -> otelprocesscontext.AnyValue
	2, // 7: otelprocesscontext.KeyValueList.values:type_name -> otelprocesscontext.KeyValue
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_processcontext_proto_init() }
func file_processcontext_proto_init() {
	if File_processcontext_proto != nil {
		return
	}
	file_processcontext_proto_msgTypes[3].OneofWrappers = []any{
		(*AnyValue_StringValue)(nil),
		(*AnyValue_BoolValue)(nil),
		(*AnyValue_IntValue)(nil),
		(*AnyValue_DoubleValue)(nil),
		(*AnyValue_ArrayValue)(nil),
		(*AnyValue_KvlistValue)(nil),
		(*AnyValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_processcontext_proto_rawDesc), len(file_processcontext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_processcontext_proto_goTypes,
		DependencyIndexes: file_processcontext_proto_depIdxs,
		MessageInfos:      file_processcontext_proto_msgTypes,
	}.Build()
	File_processcontext_proto = out.File
	file_processcontext_proto_goTypes = nil
	file_processcontext_proto_depIdxs = nil
}
