// Code generated by "stringer --type=Domain"; DO NOT EDIT.

package domainstate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Performance-0]
	_ = x[HTTP-1]
	_ = x[GRPC-2]
	_ = x[GraphQL-3]
}

const _Domain_name = "PerformanceHTTPGRPCGraphQL"

var _Domain_index = [...]uint8{0, 11, 15, 19, 26}

func (i Domain) String() string {
	if i >= Domain(len(_Domain_index)-1) {
		return "Domain(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Domain_name[_Domain_index[i]:_Domain_index[i+1]]
}
