#!/bin/bash

CURRENT_DIR=$(dirname "$0")

go generate ./...
go generate -C ./internal/orchestrion/_integration ./...
ORCHESTRION_VERSION=`cat $CURRENT_DIR/../.orchestrion-version` go generate -C ./orchestrion/all -tags=tools ./...
