// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025 Datadog, Inc.

package config

import (
	configtelemetry "github.com/DataDog/dd-trace-go/v2/internal/config/configtelemetry"
	telemetry "github.com/DataDog/dd-trace-go/v2/internal/telemetry"
	"time"
)

// Code generated by github.com/DataDog/dd-trace-go/v2/scripts/configinverter. DO NOT EDIT.

func (c *Config) CIVisibilityAgentless() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.ciVisibilityAgentless
}

func (c *Config) CIVisibilityEnabled() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.ciVisibilityEnabled
}

func (c *Config) SetCIVisibilityEnabled(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.ciVisibilityEnabled = v
	configtelemetry.Report("DD_CIVISIBILITY_ENABLED", v, origin)
}

func (c *Config) DataStreamsMonitoringEnabled() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.dataStreamsMonitoringEnabled
}

func (c *Config) SetDataStreamsMonitoringEnabled(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.dataStreamsMonitoringEnabled = v
	configtelemetry.Report("DD_DATA_STREAMS_ENABLED", v, origin)
}

func (c *Config) Debug() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.debug
}

func (c *Config) SetDebug(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.debug = v
	configtelemetry.Report("DD_TRACE_DEBUG", v, origin)
}

func (c *Config) DebugAbandonedSpans() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.debugAbandonedSpans
}

func (c *Config) SetDebugAbandonedSpans(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.debugAbandonedSpans = v
	configtelemetry.Report("DD_TRACE_DEBUG_ABANDONED_SPANS", v, origin)
}

func (c *Config) DebugStack() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.debugStack
}

func (c *Config) SetDebugStack(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.debugStack = v
	configtelemetry.Report("DD_TRACE_DEBUG_STACK", v, origin)
}

func (c *Config) DynamicInstrumentationEnabled() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.dynamicInstrumentationEnabled
}

func (c *Config) Env() string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.env
}

func (c *Config) SetEnv(v string, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.env = v
	configtelemetry.Report("DD_ENV", v, origin)
}

func (c *Config) GlobalSampleRate() float64 {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.globalSampleRate
}

func (c *Config) SetGlobalSampleRate(v float64, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.globalSampleRate = v
	configtelemetry.Report("DD_TRACE_SAMPLE_RATE", v, origin)
}

func (c *Config) Hostname() string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.hostname
}

func (c *Config) LogDirectory() string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.logDirectory
}

func (c *Config) SetLogDirectory(v string, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.logDirectory = v
	configtelemetry.Report("DD_TRACE_LOG_DIRECTORY", v, origin)
}

func (c *Config) LogStartup() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.logStartup
}

func (c *Config) SetLogStartup(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.logStartup = v
	configtelemetry.Report("DD_TRACE_STARTUP_LOGS", v, origin)
}

func (c *Config) LogsOTelEnabled() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.logsOTelEnabled
}

func (c *Config) SetLogsOTelEnabled(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.logsOTelEnabled = v
	configtelemetry.Report("DD_LOGS_OTEL_ENABLED", v, origin)
}

func (c *Config) OTLPExportMode() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.otlpExportMode
}

func (c *Config) SetOTLPExportMode(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.otlpExportMode = v
	configtelemetry.Report("OTEL_TRACES_EXPORTER", v, origin)
}

func (c *Config) OTLPTraceURL() string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.otlpTraceURL
}

func (c *Config) SetPartialFlushEnabled(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.partialFlushEnabled = v
	configtelemetry.Report("DD_TRACE_PARTIAL_FLUSH_ENABLED", v, origin)
}

func (c *Config) SetPartialFlushMinSpans(v int, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.partialFlushMinSpans = v
	configtelemetry.Report("DD_TRACE_PARTIAL_FLUSH_MIN_SPANS", v, origin)
}

func (c *Config) PeerServiceDefaultsEnabled() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.peerServiceDefaultsEnabled
}

func (c *Config) SetPeerServiceDefaultsEnabled(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.peerServiceDefaultsEnabled = v
	configtelemetry.Report("DD_TRACE_PEER_SERVICE_DEFAULTS_ENABLED", v, origin)
}

func (c *Config) ProfilerEndpoints() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.profilerEndpoints
}

func (c *Config) SetProfilerEndpoints(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.profilerEndpoints = v
	configtelemetry.Report("DD_PROFILING_ENDPOINT_COLLECTION_ENABLED", v, origin)
}

func (c *Config) ProfilerHotspotsEnabled() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.profilerHotspots
}

func (c *Config) SetProfilerHotspotsEnabled(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.profilerHotspots = v
	configtelemetry.Report("DD_PROFILING_CODE_HOTSPOTS_COLLECTION_ENABLED", v, origin)
}

func (c *Config) ReportHostname() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.reportHostname
}

func (c *Config) RetryInterval() time.Duration {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.retryInterval
}

func (c *Config) SetRetryInterval(v time.Duration, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.retryInterval = v
	configtelemetry.Report("DD_TRACE_RETRY_INTERVAL", v, origin)
}

func (c *Config) RuntimeMetricsEnabled() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.runtimeMetrics
}

func (c *Config) SetRuntimeMetricsEnabled(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.runtimeMetrics = v
	configtelemetry.Report("DD_RUNTIME_METRICS_ENABLED", v, origin)
}

func (c *Config) RuntimeMetricsV2Enabled() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.runtimeMetricsV2
}

func (c *Config) SetRuntimeMetricsV2Enabled(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.runtimeMetricsV2 = v
	configtelemetry.Report("DD_RUNTIME_METRICS_V2_ENABLED", v, origin)
}

func (c *Config) ServiceName() string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.serviceName
}

func (c *Config) SetServiceName(v string, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.serviceName = v
	configtelemetry.Report("DD_SERVICE", v, origin)
}

func (c *Config) SpanAttributeSchemaVersion() int {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.spanAttributeSchemaVersion
}

func (c *Config) SpanTimeout() time.Duration {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.spanTimeout
}

func (c *Config) SetSpanTimeout(v time.Duration, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.spanTimeout = v
	configtelemetry.Report("DD_TRACE_ABANDONED_SPAN_TIMEOUT", v, origin)
}

func (c *Config) StatsComputationEnabled() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.statsComputationEnabled
}

func (c *Config) SetStatsComputationEnabled(v bool, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.statsComputationEnabled = v
	configtelemetry.Report("DD_TRACE_STATS_COMPUTATION_ENABLED", v, origin)
}

func (c *Config) TraceID128BitEnabled() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.traceID128BitEnabled
}

func (c *Config) TraceProtocol() float64 {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.traceProtocol
}

func (c *Config) SetTraceProtocol(v float64, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.traceProtocol = v
	configtelemetry.Report("DD_TRACE_AGENT_PROTOCOL_VERSION", v, origin)
}

func (c *Config) TraceRateLimitPerSecond() float64 {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.traceRateLimitPerSecond
}

func (c *Config) SetTraceRateLimitPerSecond(v float64, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.traceRateLimitPerSecond = v
	configtelemetry.Report("DD_TRACE_RATE_LIMIT", v, origin)
}

func (c *Config) Version() string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.version
}

func (c *Config) SetVersion(v string, origin telemetry.Origin) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.version = v
	configtelemetry.Report("DD_VERSION", v, origin)
}
