// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025 Datadog, Inc.

package config

import (
	provider "github.com/DataDog/dd-trace-go/v2/internal/config/provider"
	"net/url"
	"time"
)

// Code generated by github.com/DataDog/dd-trace-go/v2/scripts/configinverter. DO NOT EDIT.

// configGenerated holds the generated configuration fields.
// It is embedded in Config and should not be used directly.
type configGenerated struct {
	// trace agent URL resolved from DD_TRACE_AGENT_URL, DD_AGENT_HOST, DD_TRACE_AGENT_PORT
	agentURL              *url.URL
	ciVisibilityAgentless bool
	// controls if the tracer is loaded with CI Visibility mode
	ciVisibilityEnabled          bool
	dataStreamsMonitoringEnabled bool
	// enables debug logging
	debug bool
	// controls if the tracer should log when old, open spans are found
	debugAbandonedSpans bool
	// enables collection of debug stack traces globally
	debugStack bool
	// controls if the target application can be modified by Dynamic Instrumentation
	dynamicInstrumentationEnabled bool
	// environment that this application runs under
	env string
	// set of enabled feature flags
	featureFlags map[string]struct{}
	// sample rate for the tracer (0.0-1.0 or NaN)
	globalSampleRate float64
	// hostname from OS or DD_TRACE_SOURCE_HOSTNAME
	hostname string
	// directory for tracer logs
	logDirectory string
	// causes various startup info to be written when the tracer starts
	logStartup bool
	// controls if the OpenTelemetry Logs SDK pipeline should be enabled
	logsOTelEnabled bool
	// indicates traces should be exported via OTLP rather than Datadog protocol
	otlpExportMode bool
	// resolved OTLP trace headers including Content-Type
	otlpHeaders map[string]string
	// OTLP collector endpoint for traces
	otlpTraceURL string
	// whether the tracer should enable partial flushing
	partialFlushEnabled        bool
	partialFlushMinSpans       int
	peerServiceDefaultsEnabled bool
	// peer service mappings
	peerServiceMappings map[string]string
	profilerEndpoints   bool
	profilerHotspots    bool
	// indicates whether hostname should be reported on spans
	reportHostname bool
	// interval between agent connection retries
	retryInterval    time.Duration
	runtimeMetrics   bool
	runtimeMetricsV2 bool
	// dynamically rename services
	serviceMappings map[string]string
	// name of this application
	serviceName string
	// span attribute schema version (also controls peerServiceDefaultsEnabled)
	spanAttributeSchemaVersion int
	// how old a span can be before logged as possible misconfiguration
	spanTimeout time.Duration
	// enables client-side stats computation (trace metrics)
	statsComputationEnabled bool
	// controls if trace IDs are generated as 128-bits or 64-bits
	traceID128BitEnabled bool
	// Datadog trace protocol version (0.4 or 1.0)
	traceProtocol float64
	// rate limit per second for traces
	traceRateLimitPerSecond float64
	version                 string
}

// loadConfigGenerated initializes all generated configuration fields from the provider.
// Fields marked custom_init are skipped here and must be initialized in loadConfig().
func (cfg *Config) loadConfigGenerated(p *provider.Provider) {
	// cfg.agentURL: skipped (custom_init)
	cfg.ciVisibilityAgentless = p.GetBool("DD_CIVISIBILITY_AGENTLESS_ENABLED", ciVisibilityAgentlessDefault)
	cfg.ciVisibilityEnabled = p.GetBool("DD_CIVISIBILITY_ENABLED", ciVisibilityEnabledDefault)
	cfg.dataStreamsMonitoringEnabled = p.GetBool("DD_DATA_STREAMS_ENABLED", dataStreamsMonitoringEnabledDefault)
	cfg.debug = p.GetBool("DD_TRACE_DEBUG", debugDefault)
	cfg.debugAbandonedSpans = p.GetBool("DD_TRACE_DEBUG_ABANDONED_SPANS", debugAbandonedSpansDefault)
	cfg.debugStack = p.GetBool("DD_TRACE_DEBUG_STACK", debugStackDefault)
	cfg.dynamicInstrumentationEnabled = p.GetBool("DD_DYNAMIC_INSTRUMENTATION_ENABLED", dynamicInstrumentationEnabledDefault)
	cfg.env = p.GetString("DD_ENV", envDefault)
	// cfg.featureFlags: skipped (custom_init)
	cfg.globalSampleRate = p.GetFloatWithValidator("DD_TRACE_SAMPLE_RATE", globalSampleRateDefault, validateSampleRate)
	// cfg.hostname: skipped (custom_init)
	cfg.logDirectory = p.GetString("DD_TRACE_LOG_DIRECTORY", logDirectoryDefault)
	cfg.logStartup = p.GetBool("DD_TRACE_STARTUP_LOGS", logStartupDefault)
	cfg.logsOTelEnabled = p.GetBool("DD_LOGS_OTEL_ENABLED", logsOTelEnabledDefault)
	// cfg.otlpExportMode: skipped (custom_init)
	// cfg.otlpHeaders: skipped (custom_init)
	// cfg.otlpTraceURL: skipped (custom_init)
	cfg.partialFlushEnabled = p.GetBool("DD_TRACE_PARTIAL_FLUSH_ENABLED", partialFlushEnabledDefault)
	cfg.partialFlushMinSpans = p.GetIntWithValidator("DD_TRACE_PARTIAL_FLUSH_MIN_SPANS", partialFlushMinSpansDefault, validatePartialFlushMinSpans)
	cfg.peerServiceDefaultsEnabled = p.GetBool("DD_TRACE_PEER_SERVICE_DEFAULTS_ENABLED", peerServiceDefaultsEnabledDefault)
	cfg.peerServiceMappings = p.GetMap("DD_TRACE_PEER_SERVICE_MAPPING", peerServiceMappingsDefault, peerServiceMappingsDelimiter)
	cfg.profilerEndpoints = p.GetBool("DD_PROFILING_ENDPOINT_COLLECTION_ENABLED", profilerEndpointsDefault)
	cfg.profilerHotspots = p.GetBool("DD_PROFILING_CODE_HOTSPOTS_COLLECTION_ENABLED", profilerHotspotsDefault)
	// cfg.reportHostname: skipped (custom_init)
	cfg.retryInterval = p.GetDuration("DD_TRACE_RETRY_INTERVAL", retryIntervalDefault)
	cfg.runtimeMetrics = p.GetBool("DD_RUNTIME_METRICS_ENABLED", runtimeMetricsDefault)
	cfg.runtimeMetricsV2 = p.GetBool("DD_RUNTIME_METRICS_V2_ENABLED", runtimeMetricsV2Default)
	cfg.serviceMappings = p.GetMap("DD_SERVICE_MAPPING", serviceMappingsDefault, serviceMappingsDelimiter)
	cfg.serviceName = p.GetString("DD_SERVICE", serviceNameDefault)
	// cfg.spanAttributeSchemaVersion: skipped (custom_init)
	cfg.spanTimeout = p.GetDuration("DD_TRACE_ABANDONED_SPAN_TIMEOUT", spanTimeoutDefault)
	cfg.statsComputationEnabled = p.GetBool("DD_TRACE_STATS_COMPUTATION_ENABLED", statsComputationEnabledDefault)
	cfg.traceID128BitEnabled = p.GetBool("DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED", traceID128BitEnabledDefault)
	// cfg.traceProtocol: skipped (custom_init)
	cfg.traceRateLimitPerSecond = p.GetFloatWithValidator("DD_TRACE_RATE_LIMIT", traceRateLimitPerSecondDefault, validateRateLimit)
	cfg.version = p.GetString("DD_VERSION", versionDefault)
}
