issuer: https://token.actions.githubusercontent.com

subject_pattern: "repo:DataDog/dd-trace-go:.*"

claim_pattern:
  repository: DataDog/dd-trace-go
  job_workflow_ref: DataDog/dd-trace-go/\.github/workflows/docker-build-and-push\.yml@.*

permissions:
  packages: write
