issuer: https://token.actions.githubusercontent.com
subject: repo:DataDog/dd-trace-go:pull_request
claim_pattern:
  job_workflow_ref: DataDog/dd-trace-go/.github/workflows/unit-integration-tests.yml@.*
  event_name: pull_request
  repository: DataDog/dd-trace-go
permissions:
  contents: read
  pull_requests: write
