issuer: https://token.actions.githubusercontent.com
subject: repo:DataDog/dd-trace-go:issues
claim_pattern:
  event_name: issues
  repository: DataDog/dd-trace-go
  job_workflow_ref: DataDog/dd-trace-go/.github/workflows/ecosystems-label-issue.yml@.*
permissions:
  contents: read
  issues: write
