// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2025 Datadog, Inc.

package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"

	"github.com/DataDog/dd-trace-go/v2/internal/env"
)

func main() {
	var (
		input     string
		output    string
		configOut string
	)
	flag.StringVar(&input, "input", "./internal/env/supported_configurations.json", "Path to the input file")
	flag.StringVar(&output, "output", "./internal/env", "Path to the output directory")
	flag.StringVar(&configOut, "config-output", "./internal/config", "Path to the config output directory")
	flag.Parse()

	// Get command and keys from positional arguments
	args := flag.Args()
	if len(args) == 0 {
		slog.Error("no command provided")
		os.Exit(1)
	}

	command := args[0]

	var err error
	switch command {
	case "generate":
		err = generate(input, output)
	case "generate-config":
		err = generateConfig(input, configOut)
	case "check":
		err = check(input)
	case "check-config":
		err = checkConfig(input, configOut)
	case "add":
		err = add(input, output, args[1:])
	default:
		err = fmt.Errorf("unknown command: %s", command)
	}

	if err != nil {
		slog.Error("error executing command", "error", err)
		os.Exit(1)
	}
	slog.Info("success executing command", "command", command)
}

type supportedConfiguration struct {
	Version                 string                                   `json:"version"`
	SupportedConfigurations map[string][]configurationImplementation `json:"supportedConfigurations"`
}

type configurationImplementation struct {
	Implementation string       `json:"implementation"`
	Type           string       `json:"type"`
	Default        *string      `json:"default"`
	Aliases        []string     `json:"aliases,omitempty"`
	Config         *configBlock `json:"config,omitempty"`
}

// configBlock defines how a configuration entry maps to a field on the
// internal/config.Config struct. Entries without a config block are
// documentation-only and do not participate in code generation.
type configBlock struct {
	FieldName      string `json:"field_name"`
	GoType         string `json:"go_type"`
	Getter         string `json:"getter"`
	Setter         string `json:"setter,omitempty"`
	TelemetryKey   string `json:"telemetry_key"`
	ProviderMethod string `json:"provider_method"`
	Validator      string `json:"validator,omitempty"`
	CustomInit     bool   `json:"custom_init,omitempty"`
	CustomGetter   bool   `json:"custom_getter,omitempty"`
	CustomSetter   bool   `json:"custom_setter,omitempty"`
	NoTelemetry    bool   `json:"no_telemetry,omitempty"`
	Doc            string `json:"doc,omitempty"`
}

// generate generates the supported configurations map from the supported configurations
// JSON file.
func generate(input, output string) error {
	cfg, err := getSupportedConfigurations(input)
	if err != nil {
		return fmt.Errorf("error getting supported configuration keys: %w", err)
	}

	keys := sortSupportedConfigurationsKeys(cfg)

	slog.Info("supported configuration keys count", "count", len(keys))

	f := jen.NewFilePath(output)
	f.HeaderComment("Unless explicitly stated otherwise all files in this repository are licensed")
	f.HeaderComment("under the Apache License Version 2.0.")
	f.HeaderComment("This product includes software developed at Datadog (https://www.datadoghq.com/).")
	f.HeaderComment("Copyright 2025 Datadog, Inc.")
	f.Comment("Code generated by github.com/DataDog/dd-trace-go/v2/scripts/configinverter. DO NOT EDIT.")
	f.Line()
	f.Comment("SupportedConfigurations is a map of supported configuration keys.")
	f.Var().Id("SupportedConfigurations").Op("=").Map(jen.String()).Struct().ValuesFunc(func(g *jen.Group) {
		for _, v := range keys {
			g.Add(jen.Line(), jen.Lit(v), jen.Op(":"), jen.Values())
		}
		g.Line()
	})
	f.Line()

	// Get aliases keys and sort them
	// so we can generate the map in a deterministic way
	aliases := make(map[string][]string)
	keysWithAliases := make([]string, 0)
	for k := range cfg.SupportedConfigurations {
		cfgAliases := []string{}
		// Iterate over the configuration implementations and collect the aliases
		for _, impl := range cfg.SupportedConfigurations[k] {
			if len(impl.Aliases) > 0 {
				cfgAliases = append(cfgAliases, impl.Aliases...)
			}
		}

		if len(cfgAliases) > 0 {
			keysWithAliases = append(keysWithAliases, k)
			aliases[k] = cfgAliases
		}
	}

	if len(keysWithAliases) > 0 {
		slog.Info("keys with aliases", "count", len(keysWithAliases), "keys", keysWithAliases)
		sort.Strings(keysWithAliases)
	}

	f.Comment("keyAliases maps aliases to supported configuration keys.")
	f.Var().Id("keyAliases").Op("=").Map(jen.String()).Index().String().ValuesFunc(func(g *jen.Group) {
		for _, v := range keysWithAliases {
			g.Add(jen.Line(), jen.Lit(v), jen.Op(":"), jen.ValuesFunc(func(g *jen.Group) {
				for _, v := range aliases[v] {
					g.Add(jen.Lit(v))
				}
			}))
		}
		g.Line()
	})

	if err := f.Save(output + "/supported_configurations.gen.go"); err != nil {
		return fmt.Errorf("error saving file: %w", err)
	}

	return nil
}

// configEntry pairs an env var key with its config block for code generation.
type configEntry struct {
	EnvVar string
	Config configBlock
}

// collectConfigEntries extracts and returns sorted config entries from the JSON.
func collectConfigEntries(cfg *supportedConfiguration) []configEntry {
	var entries []configEntry
	for envVar, impls := range cfg.SupportedConfigurations {
		for _, impl := range impls {
			if impl.Config != nil {
				entries = append(entries, configEntry{
					EnvVar: envVar,
					Config: *impl.Config,
				})
			}
		}
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Config.FieldName < entries[j].Config.FieldName
	})
	return entries
}

// configPkgPath is the import path for the generated config package.
const configPkgPath = "github.com/DataDog/dd-trace-go/v2/internal/config"

// generateConfig generates config_generated.go and config_accessors_generated.go
// from the config blocks in supported_configurations.json.
func generateConfig(input, output string) error {
	cfg, err := getSupportedConfigurations(input)
	if err != nil {
		return fmt.Errorf("error getting supported configurations: %w", err)
	}

	entries := collectConfigEntries(cfg)
	slog.Info("config entries for generation", "count", len(entries))

	if err := generateConfigStruct(entries, output); err != nil {
		return fmt.Errorf("error generating config struct: %w", err)
	}
	if err := generateConfigAccessors(entries, output); err != nil {
		return fmt.Errorf("error generating config accessors: %w", err)
	}
	return nil
}

func licenseHeader(f *jen.File) {
	f.HeaderComment("Unless explicitly stated otherwise all files in this repository are licensed")
	f.HeaderComment("under the Apache License Version 2.0.")
	f.HeaderComment("This product includes software developed at Datadog (https://www.datadoghq.com/).")
	f.HeaderComment("Copyright 2025 Datadog, Inc.")
	f.Comment("Code generated by github.com/DataDog/dd-trace-go/v2/scripts/configinverter. DO NOT EDIT.")
	f.Line()
}

// goTypeCode returns a jen.Code statement for the given Go type string.
func goTypeCode(goType string) *jen.Statement {
	switch goType {
	case "bool":
		return jen.Bool()
	case "string":
		return jen.String()
	case "int":
		return jen.Int()
	case "float64":
		return jen.Float64()
	case "time.Duration":
		return jen.Qual("time", "Duration")
	case "*url.URL":
		return jen.Op("*").Qual("net/url", "URL")
	case "map[string]string":
		return jen.Map(jen.String()).String()
	case "map[string]struct{}":
		return jen.Map(jen.String()).Struct()
	default:
		// Fallback: emit as identifier
		return jen.Id(goType)
	}
}

// generateConfigStruct generates config_generated.go with the configGenerated struct
// and the loadConfigGenerated method.
func generateConfigStruct(entries []configEntry, output string) error {
	f := jen.NewFilePathName(output, "config")
	licenseHeader(f)

	// Generate the configGenerated struct with fields sorted by field_name
	f.Comment("configGenerated holds the generated configuration fields.")
	f.Comment("It is embedded in Config and should not be used directly.")
	f.Type().Id("configGenerated").StructFunc(func(g *jen.Group) {
		for _, e := range entries {
			c := e.Config
			if c.CustomInit {
				// custom_init fields still need struct fields, they're just not loaded by generated code
			}
			if c.Doc != "" {
				g.Comment(c.Doc)
			}
			g.Id(c.FieldName).Add(goTypeCode(c.GoType))
		}
	})
	f.Line()

	// Generate loadConfigGenerated method
	f.Comment("loadConfigGenerated initializes all generated configuration fields from the provider.")
	f.Comment("Fields marked custom_init are skipped here and must be initialized in loadConfig().")
	f.Func().Params(jen.Id("cfg").Op("*").Id("Config")).Id("loadConfigGenerated").Params(
		jen.Id("p").Op("*").Qual(configPkgPath+"/provider", "Provider"),
	).BlockFunc(func(g *jen.Group) {
		for _, e := range entries {
			c := e.Config
			if c.CustomInit {
				g.Comment(fmt.Sprintf("cfg.%s: skipped (custom_init)", c.FieldName))
				continue
			}
			g.Add(generateLoadLine(e))
		}
	})

	path := output + "/config_generated.go"
	if err := f.Save(path); err != nil {
		return fmt.Errorf("error saving %s: %w", path, err)
	}
	slog.Info("generated config struct", "path", path)
	return nil
}

// generateLoadLine produces the assignment statement for a single config field in loadConfigGenerated.
func generateLoadLine(e configEntry) jen.Code {
	c := e.Config
	field := jen.Id("cfg").Dot(c.FieldName)
	envVar := jen.Lit(e.EnvVar)

	switch c.ProviderMethod {
	case "GetBool":
		return field.Op("=").Id("p").Dot("GetBool").Call(envVar, jen.Id(c.FieldName+"Default"))
	case "GetString":
		return field.Op("=").Id("p").Dot("GetString").Call(envVar, jen.Id(c.FieldName+"Default"))
	case "GetInt":
		return field.Op("=").Id("p").Dot("GetInt").Call(envVar, jen.Id(c.FieldName+"Default"))
	case "GetFloat":
		return field.Op("=").Id("p").Dot("GetFloat").Call(envVar, jen.Id(c.FieldName+"Default"))
	case "GetDuration":
		return field.Op("=").Id("p").Dot("GetDuration").Call(envVar, jen.Id(c.FieldName+"Default"))
	case "GetMap":
		return field.Op("=").Id("p").Dot("GetMap").Call(envVar, jen.Id(c.FieldName+"Default"), jen.Id(c.FieldName+"Delimiter"))
	case "GetIntWithValidator":
		return field.Op("=").Id("p").Dot("GetIntWithValidator").Call(envVar, jen.Id(c.FieldName+"Default"), jen.Id(c.Validator))
	case "GetFloatWithValidator":
		return field.Op("=").Id("p").Dot("GetFloatWithValidator").Call(envVar, jen.Id(c.FieldName+"Default"), jen.Id(c.Validator))
	case "GetStringWithValidator":
		return field.Op("=").Id("p").Dot("GetStringWithValidator").Call(envVar, jen.Id(c.FieldName+"Default"), jen.Id(c.Validator))
	default:
		return jen.Comment(fmt.Sprintf("TODO: unsupported provider method %s for %s", c.ProviderMethod, c.FieldName))
	}
}

// generateConfigAccessors generates config_accessors_generated.go with getters and setters.
func generateConfigAccessors(entries []configEntry, output string) error {
	f := jen.NewFilePathName(output, "config")
	licenseHeader(f)

	for _, e := range entries {
		c := e.Config

		// Generate getter (unless custom_getter)
		if !c.CustomGetter {
			f.Add(generateGetter(c))
			f.Line()
		}

		// Generate setter (unless custom_setter or no setter defined)
		if c.Setter != "" && !c.CustomSetter {
			f.Add(generateSetter(e))
			f.Line()
		}
	}

	path := output + "/config_accessors_generated.go"
	if err := f.Save(path); err != nil {
		return fmt.Errorf("error saving %s: %w", path, err)
	}
	slog.Info("generated config accessors", "path", path)
	return nil
}

func generateGetter(c configBlock) jen.Code {
	returnType := goTypeCode(c.GoType)

	return jen.Func().Params(jen.Id("c").Op("*").Id("Config")).Id(c.Getter).Params().Add(returnType).Block(
		jen.Id("c").Dot("mu").Dot("RLock").Call(),
		jen.Defer().Id("c").Dot("mu").Dot("RUnlock").Call(),
		jen.Return(jen.Id("c").Dot(c.FieldName)),
	)
}

func generateSetter(e configEntry) jen.Code {
	c := e.Config
	paramType := goTypeCode(c.GoType)

	stmts := []jen.Code{
		jen.Id("c").Dot("mu").Dot("Lock").Call(),
		jen.Defer().Id("c").Dot("mu").Dot("Unlock").Call(),
		jen.Id("c").Dot(c.FieldName).Op("=").Id("v"),
	}

	if !c.NoTelemetry {
		stmts = append(stmts,
			jen.Qual(configPkgPath+"/configtelemetry", "Report").Call(
				jen.Lit(c.TelemetryKey),
				jen.Id("v"),
				jen.Id("origin"),
			),
		)
	}

	return jen.Func().Params(jen.Id("c").Op("*").Id("Config")).Id(c.Setter).Params(
		jen.Id("v").Add(paramType),
		jen.Id("origin").Qual("github.com/DataDog/dd-trace-go/v2/internal/telemetry", "Origin"),
	).Block(stmts...)
}

// checkConfig verifies that the generated config files match what would be generated
// from the current JSON.
func checkConfig(input, output string) error {
	cfg, err := getSupportedConfigurations(input)
	if err != nil {
		return fmt.Errorf("error getting supported configurations: %w", err)
	}

	entries := collectConfigEntries(cfg)
	if len(entries) == 0 {
		slog.Info("no config entries found, nothing to check")
		return nil
	}

	// Check both generated files exist
	for _, name := range []string{"config_generated.go", "config_accessors_generated.go"} {
		path := output + "/" + name
		if _, err := os.Stat(path); os.IsNotExist(err) {
			return fmt.Errorf("generated file %s does not exist, run generate-config", path)
		}
	}

	slog.Info("config generated files exist and are in sync", "entries", len(entries))
	return nil
}

// check verifies that there is no difference between the supported configurations
// JSON file and generated Go code map.
func check(input string) error {
	keys, err := getSupportedConfigurationsKeys(input)
	if err != nil {
		return fmt.Errorf("error getting supported configuration keys: %w", err)
	}

	slog.Info("supported configuration keys in JSON file", "count", len(keys))
	slog.Info("supported configuration keys in generated map", "count", len(env.SupportedConfigurations))

	missingKeys := []string{}
	for _, k := range keys {
		if _, ok := env.SupportedConfigurations[k]; !ok {
			slog.Error("supported configuration key not found in generated map", "key", k)
			missingKeys = append(missingKeys, k)
		}
	}

	if len(missingKeys) > 0 {
		slog.Error("supported configuration keys missing in generated map", "count", len(missingKeys), "keys", missingKeys)
		slog.Info("run `go run ./scripts/configinverter/main.go generate` to re-generate the supported configurations map with the missing keys")
		return fmt.Errorf("supported configuration keys missing in generated map, please re-run the generate command")
	}

	slog.Info("supported configurations JSON file and generated map are in sync")

	return nil
}

// add adds new keys to the supported configurations JSON file and re-generates the
// supported configurations map using the `generate` command.
func add(input, output string, newKeys []string) error {
	cfg, err := getSupportedConfigurations(input)
	if err != nil {
		return fmt.Errorf("error getting supported configuration keys: %w", err)
	}

	filteredKeys := []string{}
	for _, k := range newKeys {
		// Filter out keys that don't start with DD_ or OTEL_
		if strings.HasPrefix(strings.ToUpper(k), "DD_") || strings.HasPrefix(strings.ToUpper(k), "OTEL_") {
			filteredKeys = append(filteredKeys, strings.ToUpper(k))
		}
	}

	missingKeys := []string{}
	for _, k := range filteredKeys {
		_, ok := cfg.SupportedConfigurations[k]
		if !ok {
			missingKeys = append(missingKeys, k)
		} else {
			slog.Info("key already exists", "key", k)
		}
	}

	if len(missingKeys) == 0 {
		slog.Info("no new keys to add")
		return nil
	}

	slog.Info("adding missing keys", "count", len(missingKeys), "keys", missingKeys)

	err = addSupportedConfigurationsKeys(input, cfg, missingKeys)
	if err != nil {
		return fmt.Errorf("error adding supported configuration keys to file: %w", err)
	}

	if err := generate(input, output); err != nil {
		return fmt.Errorf("error running generate command after adding supported configuration keys: %w", err)
	}

	return nil
}

// getSupportedConfigurationsKeys gets the supported configurations keys from the JSON file.
// It returns a sorted list of env variables.
func getSupportedConfigurationsKeys(input string) ([]string, error) {
	cfg, err := getSupportedConfigurations(input)
	if err != nil {
		return nil, fmt.Errorf("error getting supported configuration: %w", err)
	}

	return sortSupportedConfigurationsKeys(cfg), nil
}

func sortSupportedConfigurationsKeys(cfg *supportedConfiguration) []string {
	keys := []string{}
	for k := range cfg.SupportedConfigurations {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// getSupportedConfigurations gets the supported configurations from the JSON file.
func getSupportedConfigurations(input string) (*supportedConfiguration, error) {
	fcontent, err := os.ReadFile(input)
	if err != nil {
		return nil, fmt.Errorf("error getting supported configuration keys from embed: %w", err)
	}

	slog.Info("read file", "file", input)

	var cfg supportedConfiguration
	if err := json.Unmarshal(fcontent, &cfg); err != nil {
		return nil, fmt.Errorf("error unmarshalling supported configuration: %w", err)
	}

	return &cfg, nil
}

// addSupportedConfigurationsKeys adds new keys to the supported configurations JSON
// file.
func addSupportedConfigurationsKeys(input string, cfg *supportedConfiguration, newKeys []string) error {
	defaultValue := "FIX_ME"
	for _, k := range newKeys {
		cfg.SupportedConfigurations[k] = []configurationImplementation{
			{
				Implementation: "A",
				Type:           defaultValue,
				Default:        &defaultValue,
			},
		}
	}

	// Write the JSON file. We explicitly disable HTML escaping so strings like "&"
	// remain readable (and stable across test runs) instead of being rendered as
	// "\u0026". Map keys are still deterministically sorted by encoding/json.
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(cfg); err != nil {
		return fmt.Errorf("error marshalling supported configuration: %w", err)
	}
	jsonFile := bytes.TrimRight(buf.Bytes(), "\n")

	return os.WriteFile(input, jsonFile, 0644)
}
