// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.
//
// Code generated by 'go generate'; DO NOT EDIT.

package connectrpc

import (
	"testing"

	"github.com/DataDog/dd-trace-go/v2/internal/orchestrion/_integration/internal/harness"
)

func Test(t *testing.T) {
	harness.Run(t, new(TestCase))
}

func TestBidiStream(t *testing.T) {
	harness.Run(t, new(TestCaseBidiStream))
}

func TestClientStream(t *testing.T) {
	harness.Run(t, new(TestCaseClientStream))
}

func TestClientStreamSimple(t *testing.T) {
	harness.Run(t, new(TestCaseClientStreamSimple))
}

func TestNestedClientOptions(t *testing.T) {
	harness.Run(t, new(TestCaseNestedClientOptions))
}

func TestServerStream(t *testing.T) {
	harness.Run(t, new(TestCaseServerStream))
}

func TestServerStreamSimple(t *testing.T) {
	harness.Run(t, new(TestCaseServerStreamSimple))
}

func TestSharedOptions(t *testing.T) {
	harness.Run(t, new(TestCaseSharedOptions))
}

func TestUnarySimple(t *testing.T) {
	harness.Run(t, new(TestCaseUnarySimple))
}

func TestUntracedClient(t *testing.T) {
	harness.Run(t, new(TestCaseUntracedClient))
}
