// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2026 Datadog, Inc.

package connectrpc

import (
	"context"
	"sync/atomic"
	"testing"

	"connectrpc.com/connect"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/types/known/wrapperspb"

	"github.com/DataDog/dd-trace-go/v2/internal/orchestrion/_integration/internal/trace"
)

// newEchoServiceClient has the shape of a client constructor generated by protoc-gen-connect-go.
func newEchoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) *echoClient {
	return connect.NewClient[wrapperspb.StringValue, wrapperspb.StringValue](
		httpClient,
		baseURL+unaryRPC.procedure,
		connect.WithClientOptions(opts...),
	)
}

// TestCaseNestedClientOptions passes connect.WithClientOptions to a generated constructor, which
// wraps it in another connect.WithClientOptions. Both calls are woven, so the client has two
// Datadog interceptors, and it must still produce a single connect.client span.
type TestCaseNestedClientOptions struct {
	server
	httpClient        sendRecorder
	client            *echoClient
	clientIntercepted atomic.Bool
}

func (tc *TestCaseNestedClientOptions) Setup(_ context.Context, t *testing.T) {
	tc.start(t, connect.NewUnaryHandler(unaryRPC.procedure, echo))
	tc.httpClient.client = tc.srv.Client()
	tc.client = newEchoServiceClient(&tc.httpClient, tc.srv.URL,
		connect.WithClientOptions(connect.WithInterceptors(connect.UnaryInterceptorFunc(func(next connect.UnaryFunc) connect.UnaryFunc {
			return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
				tc.clientIntercepted.Store(true)
				return next(ctx, req)
			}
		}))),
	)
}

func (tc *TestCaseNestedClientOptions) Run(ctx context.Context, t *testing.T) {
	res, err := tc.client.CallUnary(ctx, connect.NewRequest(wrapperspb.String("hello")))
	require.NoError(t, err)
	require.Equal(t, "hello", res.Msg.GetValue())
	tc.stop()
	require.True(t, tc.clientIntercepted.Load(), "user client interceptor was not called")
	// The harness cannot count spans. A second connect.client span would be a child of the first
	// and active when the request is sent, so check that the active span is the trace root.
	sent := tc.httpClient.last.Load()
	require.NotNil(t, sent)
	require.True(t, sent.traced, "request sent without an active span")
	require.True(t, sent.root, "request sent under nested spans")
}

func (tc *TestCaseNestedClientOptions) ExpectedTraces() trace.Traces {
	return trace.Traces{
		tc.clientCallSpan(unaryRPC, 0,
			tc.httpClientSpan(unaryRPC,
				tc.httpServerSpan(unaryRPC,
					serverCallSpan(unaryRPC, 0),
				),
			),
		),
	}
}
