// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2026 Datadog, Inc.

package connectrpc

import (
	"context"
	"net/http"
	"sync/atomic"
	"testing"

	"connectrpc.com/connect"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/types/known/wrapperspb"

	"github.com/DataDog/dd-trace-go/v2/internal/orchestrion/_integration/internal/trace"
)

// echoServiceHandler has the shape of a service interface generated by protoc-gen-connect-go.
type echoServiceHandler interface {
	Echo(context.Context, *connect.Request[wrapperspb.StringValue]) (*connect.Response[wrapperspb.StringValue], error)
}

type echoService struct{}

func (echoService) Echo(ctx context.Context, req *connect.Request[wrapperspb.StringValue]) (*connect.Response[wrapperspb.StringValue], error) {
	return echo(ctx, req)
}

// newEchoServiceHandler has the shape of a handler constructor generated by protoc-gen-connect-go,
// which passes the caller's options through connect.WithHandlerOptions after its own.
func newEchoServiceHandler(svc echoServiceHandler, opts ...connect.HandlerOption) http.Handler {
	return connect.NewUnaryHandler(
		unaryRPC.procedure,
		svc.Echo,
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
}

// TestCase uses the shapes of generated code: an interface method value as the handler, handler
// options nested in connect.WithHandlerOptions, and client options spread into
// connect.WithClientOptions, which Orchestrion rewrites differently from plain arguments.
type TestCase struct {
	server
	client            *echoClient
	clientIntercepted atomic.Bool
	serverIntercepted atomic.Bool
}

func (tc *TestCase) Setup(_ context.Context, t *testing.T) {
	var svc echoServiceHandler = echoService{}
	tc.start(t, newEchoServiceHandler(svc, connect.WithInterceptors(connect.UnaryInterceptorFunc(func(next connect.UnaryFunc) connect.UnaryFunc {
		return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
			tc.serverIntercepted.Store(true)
			return next(ctx, req)
		}
	}))))

	clientOpts := []connect.ClientOption{
		connect.WithInterceptors(connect.UnaryInterceptorFunc(func(next connect.UnaryFunc) connect.UnaryFunc {
			return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
				tc.clientIntercepted.Store(true)
				return next(ctx, req)
			}
		})),
	}
	tc.client = connect.NewClient[wrapperspb.StringValue, wrapperspb.StringValue](
		tc.srv.Client(),
		tc.url(unaryRPC),
		connect.WithClientOptions(clientOpts...),
	)
}

func (tc *TestCase) Run(ctx context.Context, t *testing.T) {
	res, err := tc.client.CallUnary(ctx, connect.NewRequest(wrapperspb.String("hello")))
	require.NoError(t, err)
	require.Equal(t, "hello", res.Msg.GetValue())
	tc.stop()
	require.True(t, tc.clientIntercepted.Load(), "user client interceptor was not called")
	require.True(t, tc.serverIntercepted.Load(), "user handler interceptor was not called")
}

func (tc *TestCase) ExpectedTraces() trace.Traces {
	return trace.Traces{
		tc.clientCallSpan(unaryRPC, 0,
			tc.httpClientSpan(unaryRPC,
				tc.httpServerSpan(unaryRPC,
					serverCallSpan(unaryRPC, 0),
				),
			),
		),
	}
}
