// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.
//
// Code generated by 'go generate'; DO NOT EDIT.

package zap

import (
	"testing"

	"github.com/DataDog/dd-trace-go/v2/internal/orchestrion/_integration/internal/harness"
)

func TestNewLogger(t *testing.T) {
	harness.Run(t, new(TestCaseNewLogger))
}

func TestGlobalLogger(t *testing.T) {
	harness.Run(t, new(TestCaseGlobalLogger))
}

func TestSugaredLogger(t *testing.T) {
	harness.Run(t, new(TestCaseSugaredLogger))
}

func TestChildLogger(t *testing.T) {
	harness.Run(t, new(TestCaseChildLogger))
}

func TestGoroutine(t *testing.T) {
	harness.Run(t, new(TestCaseGoroutine))
}

func TestNoContext(t *testing.T) {
	harness.Run(t, new(TestCaseNoContext))
}

func TestRequestContext(t *testing.T) {
	harness.Run(t, new(TestCaseRequestContext))
}
