name: Check Pull Request CI Status

on:
  workflow_dispatch: # allow to trigger the workflow on main, to add it in suggestion on branch protection rules
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  checks: read
  statuses: read

jobs:
  all-jobs-are-green:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ensure CI Success
        uses: DataDog/ensure-ci-success@727e7fe39ae2e1ce7ea336ec85a7369ab0731754
        with:
          initial-delay-seconds: "1000"  # smoke tests takes approx 20 mn to finish
          max-retries: "60"
