name: Label APM Ecosystems issues
on:
  issues:
    paths:
      - "contrib/**"
    types:
      - reopened
      - opened
      - edited
  pull_request:
    paths:
      - "contrib/**"
    types:
      - opened
      - reopened
      - edited
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/actions-ecosystem-add-labels
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: apm:ecosystem
