name: Label APM Ecosystems issues
on:
  issues:
    types:
      - reopened
      - opened
      - edited
  pull_request:
    types:
      - opened
      - reopened
jobs:
  label_issues:
    if: contains(github.event.*.labels.*.name, 'contrib')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["apm:ecosystem"]
            })
