name: Gotip Testing

on:
  schedule: # nightly
    - cron: "0 0 * * *"
  workflow_dispatch: { } # manually

env:
  TEST_RESULTS: /tmp/tip-results # path to where test results will be saved

permissions:
  contents: read

jobs:
  test-tip:
    runs-on: ubuntu-latest
    services:
      datadog-agent:
        image: datadog/agent-dev:master-py3
        env:
          DD_HOSTNAME: "github-actions-worker"
          DD_APM_ENABLED: true
          DD_BIND_HOST: "0.0.0.0"
          DD_API_KEY: "${{ secrets.DD_API_KEY }}"
          DD_TEST_AGENT_HOST: "localhost"
          DD_TEST_AGENT_PORT: 9126
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
          repository: DataDog/dd-trace-go

      - name: Get Gotip
        run: |-
          go install golang.org/dl/gotip@latest
          echo "$HOME/go/bin" >> "$GITHUB_PATH"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

      - name: Download dependencies
        env:
          GO_CMD: gotip
        run: |-
          ./scripts/install_tools.sh --bin-dir ${{ github.workspace }}/bin
          gotip download

      - name: Run tests
        env:
          DD_APPSEC_WAF_TIMEOUT: 1h
          TEST_RESULTS: ${{ env.TEST_RESULTS }}
          GO_CMD: gotip
        run: ./scripts/ci_test_core.sh
      
      - name: Upload the results to Datadog CI App
        if: always()
        continue-on-error: true
        uses: ./.github/actions/dd-ci-upload
        with:
          dd-api-key: ${{ secrets.DD_CI_API_KEY }}
          path: ${{ env.TEST_RESULTS }}
          tags: go:gotip,arch:${{ runner.arch }},os:${{ runner.os }}

      - name: Upload Coverage
        if: always()
        continue-on-error: true
        uses: ./.github/actions/codecov-upload
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
