name: Outdated integrations

on:
#   workflow_call: # allows to reuse this workflow
#     inputs:
#       ref:
#         description: The branch or tag to run the workflow on
#         required: true
#         type: string
#       go-libddwaf-ref:
#         description: A git ref to update github.com/DataDog/go-libddwaf/v3 to. No-op if empty.
#         required: false
#         type: string
  push:
    branches: # TODO: modify this
      - 'quinna.halim/update-outdated-integrations-workflow'
#   schedule: # weekly Sunday midnight
#     - cron: "0 0 * * 0"
#   pull_request:
#     branches:
#       - '**'


jobs:
    outdated-integrations:
        name: "Update integration and dependency versions"
        runs-on: ubuntu-latest
        env:
            PACKAGES: ./internal/... ./ddtrace/... ./profiler/... ./appsec/...
        steps:
            - uses: actions/checkout@v4
            - name: get updated go.mod go.sum
              run: |
                go get -u -t $PACKAGES
                go mod tidy
            - run: git diff