name: APM Parametric Tests

on:
  workflow_call: # allows to reuse this workflow
    inputs:
      branch_ref:
        description: 'The branch to run the workflow on'
        required: true
        type: string
  push:
    branches:
      - release-v*
      - mq-working-branch-**
    tags-ignore:
      - 'contrib/**'
      - 'instrumentation/**'
      - 'internal/**'
      - 'orchestrion/**'
      - 'scripts/**'
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: 'System Tests ref/tag/branch (defaults to the pinned SYSTEM_TESTS_REF)'
        required: false
        default: ''
        type: string
  schedule:
    - cron:  '00 04 * * 2-6'

permissions:
  contents: read

env:
  SYSTEM_TESTS_REF: 9aa3c7d0fc5fdd05ca39a99f614b2e9d8c9b8f20 # Automated: Updated by .github/workflows/update-system-tests.yml.

jobs:
  parametric-tests:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == 'DataDog/dd-trace-go')
    runs-on:
      group: "APM Larger Runners"
    env:
      TEST_LIBRARY: golang
    steps:
      - name: Checkout system tests
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          repository: 'DataDog/system-tests'
          ref: ${{ inputs.ref || env.SYSTEM_TESTS_REF }}

      - name: Checkout dd-trace-go
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ inputs.branch_ref || github.ref }}
          path: 'binaries/dd-trace-go'

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "oldstable"

      - name: Build runner
        uses: ./.github/actions/install_runner

      - name: Run
        run: ./run.sh PARAMETRIC
