name: Release / Publish a new release candidate (bot)

on:
  workflow_dispatch:
    inputs:
      release-branch:
        description: 'Release branch to create release candidate from'
        required: true

jobs:
  bump_rc_and_tag:
    name: Create and publish a new release candidate version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH: ${{ github.event.inputs.release-branch }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Check the branch name
        run: |
          [[ "$BRANCH" =~ release-v[0-9]+\.[0-9]+\.x ]]

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git fetch --tags origin $BRANCH
          git checkout $BRANCH

      - name: Read the version.go file
        id: version
        run: go run .github/workflows/apps/parse/parse_version.go

      - name: Update the version.go file in the release branch to ${{ steps.version.outputs.next_rc }}
        env:
          VERSION: ${{ steps.version.outputs.next_rc }}
        run: |
          go run .github/workflows/apps/update_version_file.go $VERSION
          git add --all
          git commit -m "update version to $VERSION"

      - name: Create the git tag ${{ steps.version.outputs.next_rc }}
        env:
          VERSION: ${{ steps.version.outputs.next_rc }}
        run: git tag -m "$VERSION - Automated RC" $VERSION

      - name: Push the branch and tag
        run: git push --tags origin $BRANCH
