name: Release / Start a new minor release

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  start:
    name: Start a new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git fetch origin main
          git checkout main

      - name: Read the version.go file
        id: version
        run: go run .github/workflows/apps/parse/parse_version.go

      - name: Create the release branch release-${{ steps.version.outputs.current_without_patch }}
        env:
          BRANCH: release-${{ steps.version.outputs.current_without_patch }}
        run: |
          git checkout -b $BRANCH
          git push -u origin $BRANCH

      - name: Create the release note draft
        id: release_note
        env:
          VERSION: ${{ steps.version.outputs.current }}
          BRANCH: release-${{ steps.version.outputs.current_without_patch}}
        run: |
          url=$(gh release create $VERSION --title="$VERSION" --draft --generate-notes --target="$BRANCH" --notes-start-tag="${{ steps.version.outputs.current }}")
          echo $url
          echo "::set-output name=url::$url"


      - name: Create the next release GitHub milestone ${{ steps.version.outputs.next_minor }}
        env:
          NEXT_VERSION: ${{ steps.version.outputs.next_minor }}
        run: |
          gh api /repos/$GITHUB_REPOSITORY/milestones \
            --method POST \
            -f title="$NEXT_VERSION" \
            -f state='open' \
            -f description="Tracking milestone for version $NEXT_VERSION" || true # ignore if already exists
