# Given the schedule below, the cost per scenario per month is:
#
# envs * nightly_minutes * cost_per_minute * 30 + envs * weekly_minutes * cost_per_minute * 4
# 2 * 10 * 0.008 * 30 + 2 * 60 * 0.008 * 4 = $8.64
#
# [1] https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates
name: "Test Apps Schedule"
on:
  workflow_dispatch: # manually (just for testing the cron)
  schedule:
    - cron: "0 0 * * *" # nightly
    - cron: "0 0 * * 2" # weekly (tuesdays)

jobs:
  nightly:
    if: github.event.schedule == '0 0 * * *'
    uses: ./.github/workflows/test-apps.yml
    secrets: inherit
    with:
      "arg: scenario_duration": "10m"

  weekly:
    if: github.event.schedule == '0 0 * * 2'
    uses: ./.github/workflows/test-apps.yml
    secrets: inherit
    with:
      "arg: scenario_duration": "1h"