//
//Run this generate Go code after changing things below:
//
//protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative internal/traceprof/traceproftest/testapp/test_app.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/traceprof/traceproftest/testapp/test_app.proto

package testapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuDuration   int64                  `protobuf:"varint,1,opt,name=cpu_duration,json=cpuDuration,proto3" json:"cpu_duration,omitempty"`
	SqlDuration   int64                  `protobuf:"varint,2,opt,name=sql_duration,json=sqlDuration,proto3" json:"sql_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkReq) Reset() {
	*x = WorkReq{}
	mi := &file_internal_traceprof_traceproftest_testapp_test_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkReq) ProtoMessage() {}

func (x *WorkReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_traceprof_traceproftest_testapp_test_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkReq.ProtoReflect.Descriptor instead.
func (*WorkReq) Descriptor() ([]byte, []int) {
	return file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDescGZIP(), []int{0}
}

func (x *WorkReq) GetCpuDuration() int64 {
	if x != nil {
		return x.CpuDuration
	}
	return 0
}

func (x *WorkReq) GetSqlDuration() int64 {
	if x != nil {
		return x.SqlDuration
	}
	return 0
}

type WorkRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpanId        string                 `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRes) Reset() {
	*x = WorkRes{}
	mi := &file_internal_traceprof_traceproftest_testapp_test_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRes) ProtoMessage() {}

func (x *WorkRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_traceprof_traceproftest_testapp_test_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRes.ProtoReflect.Descriptor instead.
func (*WorkRes) Descriptor() ([]byte, []int) {
	return file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDescGZIP(), []int{1}
}

func (x *WorkRes) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

var File_internal_traceprof_traceproftest_testapp_test_app_proto protoreflect.FileDescriptor

const file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDesc = "" +
	"\n" +
	"7internal/traceprof/traceproftest/testapp/test_app.proto\x12\atestapp\"O\n" +
	"\aWorkReq\x12!\n" +
	"\fcpu_duration\x18\x01 \x01(\x03R\vcpuDuration\x12!\n" +
	"\fsql_duration\x18\x02 \x01(\x03R\vsqlDuration\"\"\n" +
	"\aWorkRes\x12\x17\n" +
	"\aspan_id\x18\x01 \x01(\tR\x06spanId27\n" +
	"\aTestApp\x12,\n" +
	"\x04Work\x12\x10.testapp.WorkReq\x1a\x10.testapp.WorkRes\"\x00BLZJgithub.com/DataDog/dd-trace-go/v2/internal/traceprof/traceproftest/testappb\x06proto3"

var (
	file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDescOnce sync.Once
	file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDescData []byte
)

func file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDescGZIP() []byte {
	file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDescOnce.Do(func() {
		file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDesc), len(file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDesc)))
	})
	return file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDescData
}

var file_internal_traceprof_traceproftest_testapp_test_app_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_traceprof_traceproftest_testapp_test_app_proto_goTypes = []any{
	(*WorkReq)(nil), // 0: testapp.WorkReq
	(*WorkRes)(nil), // 1: testapp.WorkRes
}
var file_internal_traceprof_traceproftest_testapp_test_app_proto_depIdxs = []int32{
	0, // 0: testapp.TestApp.Work:input_type -> testapp.WorkReq
	1, // 1: testapp.TestApp.Work:output_type -> testapp.WorkRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_traceprof_traceproftest_testapp_test_app_proto_init() }
func file_internal_traceprof_traceproftest_testapp_test_app_proto_init() {
	if File_internal_traceprof_traceproftest_testapp_test_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDesc), len(file_internal_traceprof_traceproftest_testapp_test_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_traceprof_traceproftest_testapp_test_app_proto_goTypes,
		DependencyIndexes: file_internal_traceprof_traceproftest_testapp_test_app_proto_depIdxs,
		MessageInfos:      file_internal_traceprof_traceproftest_testapp_test_app_proto_msgTypes,
	}.Build()
	File_internal_traceprof_traceproftest_testapp_test_app_proto = out.File
	file_internal_traceprof_traceproftest_testapp_test_app_proto_goTypes = nil
	file_internal_traceprof_traceproftest_testapp_test_app_proto_depIdxs = nil
}
